INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (1, 'mission2', 'blackdew', 'F0001', UNIX_TIMESTAMP('2008-12-03 21:56:42'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (3, 'mission2', 'npngjjh', 'F0001', UNIX_TIMESTAMP('2008-12-19 16:25:45'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (22, 'mission2', 'lovehouse', 'F0001', UNIX_TIMESTAMP('2009-11-19 22:17:38'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (23, 'test', 'lovehouse', 'F0002', UNIX_TIMESTAMP('2009-11-19 22:29:46'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (31, 'mwkang1024', 'wany505', 'F0002', UNIX_TIMESTAMP('2010-03-07 18:01:04'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (35, 'mission001', 'butnow', 'F0002', UNIX_TIMESTAMP('2010-03-12 21:43:35'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (37, 'mwkang1024', 'glh811', 'F0002', UNIX_TIMESTAMP('2010-04-08 01:17:42'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (57, 'mission001', 'lovehouse', 'F0002', UNIX_TIMESTAMP('2010-06-23 22:12:09'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (58, 'mwkang1024', 'lovehouse', 'F0002', UNIX_TIMESTAMP('2010-06-23 22:26:29'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (61, 'mission001', 'wmpkorea', 'F0002', UNIX_TIMESTAMP('2011-11-23 05:42:09'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (62, 'myanmagape', 'lovehouse', 'F0002', UNIX_TIMESTAMP('2012-05-03 21:27:59'));

INSERT INTO family
  (id, userid, followuserid, familyType, regDate)
VALUES
  (65, 'jhouse1', 'lovehouse', 'F0002', UNIX_TIMESTAMP('2013-03-19 11:20:57'));

