
INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('adama65', 'ftvpi4322xceph', 4, '세종고등학교', '이봉우', '아다마', 3, 'his-people@hanmail.net', '', '', '', '', '02--', '010--', 0, UNIX_TIMESTAMP('2013-05-21 18:03:25'), UNIX_TIMESTAMP('2013-05-21 18:03:25'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('apple802', 'ftvpi319fmqqbeph', 7, '강대준', '강성숙', '사과', 3, 'albkss@yahoo.co.kr', '6408022630016', '경기 고양시 덕양구 관산동', '68번지', '412802', '031-964-8580', '010--', 0, UNIX_TIMESTAMP('2009-12-07 03:44:34'), UNIX_TIMESTAMP('2009-12-07 03:44:34'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('bark2028', 'ftvpiouQesmxiejeoggqgglheph', 5, '오직예수', '박기철', '동트는바다', 3, 'barkgichul@hanmail.net', '6302281110713', '대구 남구 대명9동', '481-3번지', '705803', '053-655-8024', '010-3882-8024', 1, UNIX_TIMESTAMP('2012-02-08 12:59:11'), UNIX_TIMESTAMP('2012-02-08 12:59:11'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('bearsfc', 'ftvpi65:622tmeevseph', 1, '경인115945', '김경인', '곰도사', 1, 'bearsfc2@gmail.com', '7209081120428', '', '', '', '02--', '010--', 0, UNIX_TIMESTAMP('2012-08-04 00:32:23'), UNIX_TIMESTAMP('2012-08-04 00:32:23'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('bkkace', 'ftvpi888opmpdeph', 7, '박재홍', '박기정', 'bkkace', 1, 'kingpkj@yahoo.co.kr', '6605101912311', '경남 진주시 상평동', '동국2차 1805', '660902', '02--', '010-9949-9451', 0, UNIX_TIMESTAMP('2012-02-16 10:59:33'), UNIX_TIMESTAMP('2012-02-16 10:59:33'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('blackdew', 'ftvpi2222eph', 1, '1111', '이숙번', '블랙듀', 3, 'blackdew7@gmail.com', '7902271011215', '서울 강남구 수서동 신동아아파트', '701동 805호', '135782', '070-8118-6800', '010-8724-9504', 0, UNIX_TIMESTAMP('2008-11-04 23:58:25'), UNIX_TIMESTAMP('2008-11-04 23:58:25'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('butnow', 'ftvpi4361tmxeph', 1, '이효진', '윤성재', 'butnow', 7, 'butnow@daum.net', '7311301906515', '경북 경산시 조영동', '1111', '712270', '02--', '010-2929-9451', 1, UNIX_TIMESTAMP('2010-03-12 21:41:08'), UNIX_TIMESTAMP('2010-03-12 21:41:08'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('cman007', 'ftvpi811tmxeveeph', 7, '김우협', '김영진', '성북동김', 1, 'tangjin@empal.com', '8101181036115', '서울 성북구 성북동', '173-45호 2층', '136020', '070-7520-7460', '010-4574-7460', 1, UNIX_TIMESTAMP('2010-02-03 19:16:09'), UNIX_TIMESTAMP('2010-02-03 19:16:09'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('dawnwatchmission', 'ftvpi4621eph', 7, '김병한', '김갑동', 'ptr kim', 3, 'dawnwatchmission@yahoo.com', '4612271400217', '서울 노원구 상계6.7동 노원구청', '벽산 3차 102동 1804호', '139703', '070-8246-1011', '010-4103-4413', 0, UNIX_TIMESTAMP('2013-02-12 13:46:00'), UNIX_TIMESTAMP('2013-02-12 13:46:00'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('dongjae', 'ftvpi938bbboeph', 7, '아부지', '이동재', '찌질이', 1, 'dongjae3091@hanmail.net', '7909271019121', '서울 성동구 금호동1가 벽산아파트', '201동 403호', '133778', '02-2294-0609', '010-9271-8907', 1, UNIX_TIMESTAMP('2010-04-06 14:32:47'), UNIX_TIMESTAMP('2010-04-06 14:32:47'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('dongsuh316', 'ftvpi6917ivthopeeph', 0, '', '김서연', '동서산부인과', 7, 'dongshu316@hanmail.net', '111111', '', '', '', '02--', '010-2951-0778', 1, UNIX_TIMESTAMP('2012-02-16 08:50:04'), UNIX_TIMESTAMP('2012-02-16 08:50:04'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('dosungoo', 'ftvpi88883:4peeph', 1, '덕전', '도바울', '주찬양', 3, 'dosungoo@naver.com', '6412151478233', '대전 동구 삼성동', '391-3', '300170', '042-631-0653', '010-3208-7300', 1, UNIX_TIMESTAMP('2012-05-11 14:06:42'), UNIX_TIMESTAMP('2012-05-11 14:06:42'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('fimsoo', 'ftvpi:131eph', 0, '', '김성수', '이라니안', 3, 'm77m77@hanmail.net', '', '', '', '', '070-8268-9636', '010--', 0, UNIX_TIMESTAMP('2013-05-18 17:37:43'), UNIX_TIMESTAMP('2013-05-18 17:37:43'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('gardenv', 'ftvpi5112fwpmeph', 7, '이상직', '이정원', 'angel^^', 1, 'gardenv@hanmail.net', '7209012069031', '서울 서초구 서초동', '1321-11 플래티넘타워 16층 서초지점', '137070', '02-3473-7022', '010-3472-6018', 0, UNIX_TIMESTAMP('2010-11-08 14:23:52'), UNIX_TIMESTAMP('2010-11-08 14:23:52'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('gebachoi', 'ftvpi444jpideph', 5, '김시진', '최석빈', 'Geba', 1, 'rothem486@nate.com', '8310271903517', '서울 광진구 구의2동', '57-3번지 101호', '143818', '02--', '010-2043-1769', 1, UNIX_TIMESTAMP('2010-02-06 18:59:34'), UNIX_TIMESTAMP('2010-02-06 18:59:34'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('glh811', 'ftvpibxxpxeph', 8, '안기묘', '정진화', '지강애비', 1, 'npngjjh@nate.com', '7210091889710', '경기 군포시 오금동 한라2차아파트', '412동 1602호', '435760', '02--', '010-8591-6394', 1, UNIX_TIMESTAMP('2010-04-01 20:23:55'), UNIX_TIMESTAMP('2010-04-01 20:23:55'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('heeyeon86', 'ftvpimetvemnheph', 1, '김선비', '박희연', '박희연', 7, 'heeyeon86@hanmail.net', '1111111111111', '', '', '', '02--', '010-3462-9062', 1, UNIX_TIMESTAMP('2012-09-24 17:21:02'), UNIX_TIMESTAMP('2012-09-24 17:21:02'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('hisdea', 'ftvpi321mxtnetlheph', 2, '갈현초등학교', '윤성환', 'HISDEA', 7, 'hisdea@me.com', '', '서울 관악구 신림동', '251-347 수원룸 102호', '151010', '070-000-0000', '010-6646-1324', 0, UNIX_TIMESTAMP('2013-07-23 19:49:35'), UNIX_TIMESTAMP('2013-07-23 19:49:35'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('hj2jc', 'ftvpi189:uvcuvceph', 5, '윤성재', '이효진', 'hj2jc', 1, 'hj2jc@hanmail.net', '8005232925419', '경남 진주시 하대동', '현대아파트 107동 402호', '660330', '02--', '017-550-4171', 1, UNIX_TIMESTAMP('2010-04-09 02:21:13'), UNIX_TIMESTAMP('2010-04-09 02:21:13'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('hopesfc', 'ftvpi3151injleph', 5, '가언', '김혁', 'Adam', 1, 'khyeak@liberty.edu', '6808231829518', '경남 진주시 인사동', '146-6', '660020', '070-8235-6429', '010--', 0, UNIX_TIMESTAMP('2010-12-09 22:07:47'), UNIX_TIMESTAMP('2010-12-09 22:07:47'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('hw8157', 'ftvpi:513xieph', 1, 'hw2049', '이희원', '희횰', 7, 'hw8157@hanmail.ner', '8108022069010', '서울 동작구 상도1동', '463-13번지 에이스빌라 401호', '156830', '070-4319-7490', '010-2224-8157', 1, UNIX_TIMESTAMP('2012-02-18 18:45:22'), UNIX_TIMESTAMP('2012-02-18 18:45:22'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('igood', 'ftvpi511:232leph', 2, '상리초', '고종원', '평생섬김간사', 1, 'kjwigood@gmail.com', '5807031019213', '경기 고양시 일산동구 중산동', '25-83 혜성빌라 201호', '410831', '070-8200-8089', '010-4751-9004', 1, UNIX_TIMESTAMP('2012-08-31 01:37:12'), UNIX_TIMESTAMP('2012-08-31 01:37:12'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('issteel', 'ftvpiuqtkytmeeph', 7, '최학도', '최진호', '최바울', 1, 'ilsin-steel@hanmail.net', '6009201703811', '경북 영덕군 남정면 부경리', '10-1 그리심 빌리지', '766843', '070-4200-1619', '010-8541-2426', 1, UNIX_TIMESTAMP('2011-12-20 00:21:18'), UNIX_TIMESTAMP('2011-12-20 00:21:18'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('isvic9009', 'ftvpiq:1pj9eph', 5, 'David', '이인섭', 'David', 1, 'skyperfumery@gmail.com', '6703141025337', '서울 성북구 월곡2동', '50-6', '136865', '02--', '010--', 0, UNIX_TIMESTAMP('2011-06-27 13:35:43'), UNIX_TIMESTAMP('2011-06-27 13:35:43'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('jang', 'ftvpi6127eph', 7, '윤장오', '윤장오', 'joseph', 3, 'jangoh7@net', '6205011565616', '전남 목포시 명륜동', '1-10', '530270', '02--', '010-4925-8354', 0, UNIX_TIMESTAMP('2010-12-25 18:04:40'), UNIX_TIMESTAMP('2010-12-25 18:04:40'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('jhchoi315', 'ftvpi1tohpxmideph', 8, '김순남', '최재훈', '아름다운 청년', 1, 'jhchoi315@naver.com', '5903151094225', '경남 양산시 덕계동 대승하이아트아파트', '203동  802호', '626712', '055-387-0095', '010-5205-2703', 1, UNIX_TIMESTAMP('2012-06-11 23:46:00'), UNIX_TIMESTAMP('2012-06-11 23:46:00'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('jhouse', 'ftvpiftvpikeph', 0, '', '정진화', '지강애비', 7, 'npngjjh@nate.com', '721009', '', '', '', '02--', '010-8591-6394', 1, UNIX_TIMESTAMP('2012-10-07 01:11:49'), UNIX_TIMESTAMP('2012-10-07 01:11:49'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('jhouse1', 'ftvpi2ftvpikeph', 0, '', '정진화', '선교사', 3, 'godlovehouse@nate.com', '721009', '경기 군포시 산본2동 럭키백합아파트', '1125', '435743', '02--', '010-8591-6394', 0, UNIX_TIMESTAMP('2012-10-10 22:40:49'), UNIX_TIMESTAMP('2012-10-10 22:40:49'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('joe71', 'ftvpi9885fpkeph', 0, '', '정양수', '정양수', 3, 'endeavour4kg@gmail.com', '7104271483217', '', '', '', '02--', '010--', 0, UNIX_TIMESTAMP('2012-07-20 15:41:46'), UNIX_TIMESTAMP('2012-07-20 15:41:46'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('joyce', 'ftvpi864864eph', 2, '발산', '권효림', '77ㅑ77ㅑ', 1, 'kwonsea527@naver.com', '8405272188011', '서울 마포구 신수동', '250-3 201호', '121856', '032-891-2402', '010-2064-1478', 1, UNIX_TIMESTAMP('2010-04-07 14:32:20'), UNIX_TIMESTAMP('2010-04-07 14:32:20'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('jstruth', 'ftvpi1136tkeph', 7, '김덕봉', '김종수', '산유화', 7, 'jstruth@hanmail.net', '6708251915310', '경남 산청군 단성면 방목리', '산 163-28', '666', '055-974-3737', '010-3238-5110', 0, UNIX_TIMESTAMP('2010-01-17 07:59:41'), UNIX_TIMESTAMP('2010-01-17 07:59:41'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('jungjinx', 'ftvpiyy3291eph', 5, 'xx', '정진', '정진x', 1, 'your_news@naver.com', '8106061023719', '경기 군포시 대야미동', '653-5 대민오피빌딩 801호', '435060', '070-4132-0811', '010-7348-1001', 1, UNIX_TIMESTAMP('2010-07-18 23:17:31'), UNIX_TIMESTAMP('2010-07-18 23:17:31'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('junglegirl', 'ftvpipt33pneph', 5, 'mo22so', '김지민', 'junglegirl', 1, 'jeeminkim513@gmail.com', '8705132064211', '경북 포항시 북구 흥해읍 한동대학교', '상담사회복지학부 20600162', '791708', '02--', '010-6588-2175', 1, UNIX_TIMESTAMP('2009-12-05 21:27:45'), UNIX_TIMESTAMP('2009-12-05 21:27:45'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('jw1104', 'ftvpioEeiXtlHeph', 7, '이름', '한종우', '아부유스프', 1, 'jw1104@gmail.com', '', '서울 구로구 구로4동', '770-56  5층', '152873', '070-8623-9906', '010--', 0, UNIX_TIMESTAMP('2013-08-06 02:57:18'), UNIX_TIMESTAMP('2013-08-06 02:57:18'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('kevin', 'ftvpi99:792eph', 1, '정진화', '정지강', '정지강', 1, 'npngjjh@nate.com', '0202260202261', '경기 산본', '아파트', '435760', '031-395-4203', '010-8591-6394', 0, UNIX_TIMESTAMP('2010-02-09 08:54:32'), UNIX_TIMESTAMP('2010-02-09 08:54:32'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('kimsun19', 'ftvpi:2njleph', 2, '서울용암', '김선필', '건강행복', 1, 'k_sunpil@hanmail.net', '', '인천 계양구 귤현동', '488-6', '407350', '02--', '010-5643-3539', 0, UNIX_TIMESTAMP('2013-05-13 11:44:03'), UNIX_TIMESTAMP('2013-05-13 11:44:03'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('kje1982', 'ftvpigetbeph', 8, '임세정', '강지은', '강지은', 1, 'kje1982@hotmail.com', '8208172075810', '서울 서초구 서초4동 서초래미안아파트', '104-1204', '137775', '02--', '010-9884-6312', 0, UNIX_TIMESTAMP('2010-03-11 21:17:04'), UNIX_TIMESTAMP('2010-03-11 21:17:04'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('ksmkka', 'ftvpi3583leph', 6, 'kk', '김성민', '하늘사랑', 1, 'ksmkka@empal.com', '7311161093919', '서울 도봉구 방학3동 신동아1단지아파트', '13동 706호', '132762', '02--', '016-402-8482', 0, UNIX_TIMESTAMP('2009-09-22 12:19:41'), UNIX_TIMESTAMP('2009-09-22 12:19:41'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('leeki7', 'ftvpi3113jlmeph', 7, '이기화', '이강인', 'leeki7', 1, 'leeki7@chol.com', '7412061829811', '경남 진주시 초전동', '530 진주동명고', '660985', '055-752-4393', '010-3133-7461', 1, UNIX_TIMESTAMP('2010-04-12 19:26:20'), UNIX_TIMESTAMP('2010-04-12 19:26:20'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('ljr1225', 'ftvpi33sigeixeph', 6, '버섯돌이', '이종록', '버섯돌이', 1, 'ljr1225@chol.com', '7212251830014', '경기 군포시 오금동 한라1차아파트', '403동 401호', '435759', '031-394-4790', '010-9252-9262', 0, UNIX_TIMESTAMP('2010-06-30 14:14:01'), UNIX_TIMESTAMP('2010-06-30 14:14:01'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('loveemrdud', 'ftvpi864192oobeph', 1, 'ANN', '권득영', '오솔길', 1, 'loveemrdud@hanmail.net', '', '서울 관악구 봉천동', '180-357번지 효성빌라 B01호', '151050', '02-876-1114', '010-9470-1928', 0, UNIX_TIMESTAMP('2013-07-04 12:39:05'), UNIX_TIMESTAMP('2013-07-04 12:39:05'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('lovehouse', 'ftvpi5:47eph', 1, 'rlaxogmlwjswlgus', '정진화', '문지기', 9, 'godlovehouse@gmail.com', '', '경기 군포시 산본2동 럭키백합아파트', '1125동 1302호', '435743', '02-000-0000', '010-8591-6394', 0, UNIX_TIMESTAMP('2008-10-30 00:00:00'), UNIX_TIMESTAMP('2008-10-30 00:00:00'), UNIX_TIMESTAMP('2008-10-30 00:00:00'));

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('luvtravis', 'ftvpi37633beph', 2, '상인초', '임혜원', 'hyewonny', 1, 'hyewonny0103@gmail.com', '8201032075032', '경기 의왕시 고천동', '517 영광A 307호', '437010', '02--', '010-7321-0103', 1, UNIX_TIMESTAMP('2010-04-29 22:47:17'), UNIX_TIMESTAMP('2010-04-29 22:47:17'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('m10003', 'ftvpieph', 0, '', '주신실', '주신실', 3, 'ksiran0423@hanmail.net', '7305102392325', '인천 남동구 논현동', '13-11 범천빌딩 3층', '405847', '043-881-0613', '010--', 0, UNIX_TIMESTAMP('2010-11-11 15:02:04'), UNIX_TIMESTAMP('2010-11-11 15:02:04'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('m2000210135', 'ftvpi12161216heph', 0, '', '신명철', 'capian', 3, 'witness4u@hanmail.net', '', '', '', '', '02--', '010--', 0, UNIX_TIMESTAMP('2013-08-09 12:20:42'), UNIX_TIMESTAMP('2013-08-09 12:20:42'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('maria3927', 'ftvpi2424nneph', 2, '문기', '배창숙', '호호마마', 1, 'maria3927@hanmail.net', '', '서울 구로구 오류2동', '146-3번지  202호', '152896', '070-8683-3036', '010-3601-8683', 1, UNIX_TIMESTAMP('2013-04-27 20:50:41'), UNIX_TIMESTAMP('2013-04-27 20:50:41'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('mexicanspicy', 'ftvpizxk9897eph', 2, '함월초', '정우영', 'mexicanspicy', 1, 'mexicanspicy@naver.com', '8307191121711', '서울 강남구 역삼동', '637-42 402호', '135080', '02--', '010-4814-6788', 0, UNIX_TIMESTAMP('2011-11-09 17:38:51'), UNIX_TIMESTAMP('2011-11-09 17:38:51'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('mission001', 'ftvpi211ftvpifwpmeph', 1, '001', '윤구행', '윤구행', 3, 'npngjjh@nate.com', '6402021889710', '서울 서초구 잠원동', '505-5', '137906', '02--', '010--', 0, UNIX_TIMESTAMP('2010-03-09 09:37:51'), UNIX_TIMESTAMP('2010-03-09 09:37:51'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('mission2', 'ftvpi22222eph', 1, '11111', 'mission2', 'mission2', 3, '11@1111', '1111111111111', '경기 의왕시 오전동 대명구름채아파트', '111', '437752', '02-111-11', '010-1111-111', 0, UNIX_TIMESTAMP('2008-11-21 20:55:58'), UNIX_TIMESTAMP('2008-11-21 20:55:58'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('mnb2046', 'ftvpi1369coneph', 2, '남대문', '이병곤', '예들지기', 7, 'sjk2046@naver.com', '6910021004817', '서울 중구 신당5동', '67-302 진흥하이츠 빌라 401호', '100818', '070-8254-0508', '010-2449-0545', 1, UNIX_TIMESTAMP('2012-07-25 16:30:07'), UNIX_TIMESTAMP('2012-07-25 16:30:07'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('mwkang1024', 'ftvpi5312eph', 1, '정진화', '강명원', '여호수아', 3, 'mwkang1024@hanmail.net', '7010241111111', '전남 광양시 성황동', '721번지', '545050', '061-791-5227', '010--', 0, UNIX_TIMESTAMP('2010-02-23 09:58:05'), UNIX_TIMESTAMP('2010-02-23 09:58:05'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('myanmagape', 'ftvpitjkiel5116eph', 8, '신경신', '강대현', 'myanma kang', 3, 'myanmagape@gmail.com', '6310131621614', '서울 서초구 방배동', '1088번지 대우효령(아) 102-202', '137060', '02--', '010-6490-6310', 0, UNIX_TIMESTAMP('2011-05-14 10:51:37'), UNIX_TIMESTAMP('2011-05-14 10:51:37'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('nayang1211', 'ftvpi8259513beph', 4, '대원여자고등학교', '박양희', '양양', 1, 'yangyang1211@hanmail.net', '9012112048417', '서울 광진구 중곡2동', '49-41', '143885', '02-457-6133', '010-3539-1201', 1, UNIX_TIMESTAMP('2012-10-10 23:38:13'), UNIX_TIMESTAMP('2012-10-10 23:38:13'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('newacts', 'ftvpi2:27fwpmpteph', 2, '회원', '강환석', '디사랑', 3, 'hotsolove@hotmail.com', '6606011822515', '경남 마산시 회원2동', '388', '630822', '055-247-6082', '010--', 0, UNIX_TIMESTAMP('2010-07-11 15:15:08'), UNIX_TIMESTAMP('2010-07-11 15:15:08'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('npng0803', 'ftvpitmbelseph', 2, '상덕초등학교', '최연희', '강민맘', 1, 'npng0803@hanmail.net', '7303032918918', '경기 군포시 오금동 한라2차아파트', '412-1602', '435760', '031-395-4203', '010-3171-6184', 1, UNIX_TIMESTAMP('2010-03-09 10:25:07'), UNIX_TIMESTAMP('2010-03-09 10:25:07'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('paxgospel', 'ftvpi3113sbfzeph', 2, '소양초등학교', '김성은', 'paxgospel', 1, 'paxgospel@hanmail.net', '8901271030410', '', '', '', '02--', '010-9137-3870', 1, UNIX_TIMESTAMP('2013-02-11 14:55:11'), UNIX_TIMESTAMP('2013-02-11 14:55:11'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('powersfn', 'ftvpi189:eph', 7, '윤구행', '윤성복', '샬롬예루살렘', 3, 'powersfn@paran.com', '7612071930013', '광주 남구 진월동 한신아파트', '203-402', '503753', '062-433-0388', '010-2920-9742', 0, UNIX_TIMESTAMP('2012-02-12 05:02:24'), UNIX_TIMESTAMP('2012-02-12 05:02:24'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('proverbs36', 'ftvpi82815322eph', 5, '아내와 나의 생일', '배석우', '생각해주시므로', 3, 'proverbs36@hanmail.net', '771124', '', '', '', '02--', '010-4183-2116', 0, UNIX_TIMESTAMP('2012-10-25 17:02:25'), UNIX_TIMESTAMP('2012-10-25 17:02:25'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('pumsung', 'ftvpi2:51eph', 7, '박노익', '박판기', '아름다운 품성', 1, 'pumsung@gmail.com', '6709211002411', '경기 안양시 동안구 평촌동', '삼아아파트 101동 902호', '431070', '02--', '010-2433-0491', 0, UNIX_TIMESTAMP('2011-11-05 23:21:19'), UNIX_TIMESTAMP('2011-11-05 23:21:19'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('rani', 'ftvpi78245::vzseph', 7, '유태현', '유혜란', 'rani', 1, 'my_momo@hanmail.net', '8011132183110', '서울 서초구 서초4동 서초래미안아파트', '107-802', '137775', '02-594-3685', '010-2314-3685', 1, UNIX_TIMESTAMP('2009-01-05 02:31:10'), UNIX_TIMESTAMP('2009-01-05 02:31:10'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('rebecca0253', 'ftvpi9:4:HOVKeph', 2, '가락초등학교', '황정경', 'rebecca', 1, 'rebecca0253@hotmail.com', '7811192019121', '경기 고양시 일산서구 일산3동 후곡마을2단지아파트', '202-1102', '411730', '02--', '010-4255-0253', 0, UNIX_TIMESTAMP('2010-03-01 20:09:50'), UNIX_TIMESTAMP('2010-03-01 20:09:50'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('rebekahre', 'ftvpi6zflopneph', 8, '박현애', '김조은', 'rebekahre', 3, 'rebekahre@gmail.com', '', '', '', '', '02--', '010-8612-3213', 0, UNIX_TIMESTAMP('2013-07-16 13:11:03'), UNIX_TIMESTAMP('2013-07-16 13:11:03'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('sarangcn', 'ftvpibn8331eph', 7, '윤인선', '윤재훈', '쿤밍', 3, 'sarangcn@naver.com', '6807191019015', '', '', '', '02--', '010--', 0, UNIX_TIMESTAMP('2012-01-15 02:56:13'), UNIX_TIMESTAMP('2012-01-15 02:56:13'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('sisimi1', 'ftvpi44:8jneph', 4, '진주대아고등학교', '류형철', '시심이', 1, 'sisimi1@hanmail.net', '7307071108812', '경남 양산시 주남동', '신원아침도시 106동 405호', '626300', '070-4090-5869', '010-9281-5869', 1, UNIX_TIMESTAMP('2010-12-16 21:33:49'), UNIX_TIMESTAMP('2010-12-16 21:33:49'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('sjk2046', 'ftvpi1369lkteph', 2, '남대문 국민학교', '이병곤', '하늘소망', 1, 'sjk2046@naver.com', '6910021004817', '서울 중구 신당5동', '67-302 진흥하이츠빌라 401호', '100818', '070-8254-0508', '010-2449-0545', 0, UNIX_TIMESTAMP('2011-03-10 23:42:00'), UNIX_TIMESTAMP('2011-03-10 23:42:00'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('song567', 'ftvpiikt7671eph', 7, '송영도', '송재홍', '송간사', 1, 'song567@hanmail.net', '6601211930811', '경기 안산시 상록구 건건동', '554-2 겔러리 D-201', '426210', '070-8616-0656', '010-3347-0656', 0, UNIX_TIMESTAMP('2009-11-16 16:25:26'), UNIX_TIMESTAMP('2009-11-16 16:25:26'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('stu3248', 'ftvpi2:2:ffcobeeph', 1, '짝꿍', '김은우', '비전', 1, 'stu3248@nate.com', '9209012403118', '대전 유성구 장대동', '359-1번지', '305308', '042-433-3333', '010-4030-9291', 0, UNIX_TIMESTAMP('2012-11-30 14:32:38'), UNIX_TIMESTAMP('2012-11-30 14:32:38'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('sw0927', 'ftvpi795311xteph', 4, '경북고등학교', '백성욱', '감사한선교관', 1, 'sw0927@kfhi.or.kr', '8209271807915', '서울 강서구 염창동', '267-23 기아대책 2층', '157863', '02-2085-8181', '010-5336-9245', 1, UNIX_TIMESTAMP('2012-06-26 16:28:55'), UNIX_TIMESTAMP('2012-06-26 16:28:55'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('tabler74', 'ftvpi211zlteph', 2, '남당초등학교', '오요섭', '예사랑', 7, 'tabler74@daum.net', '7409061396547', '서울 강남구 삼성동', '54-2 청진상가 305호', '135090', '02-511-1040', '010-8478-7005', 0, UNIX_TIMESTAMP('2012-10-11 14:16:57'), UNIX_TIMESTAMP('2012-10-11 14:16:57'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('test', 'ftvpinynuqyeph', 0, '', '테스트', 'test', 1, 'npngjjh@nate.com', '', '', '', '', '02--', '010--', 0, UNIX_TIMESTAMP('2013-05-10 12:07:21'), UNIX_TIMESTAMP('2013-05-10 12:07:21'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('timlee', 'ftvpi7612tneph', 0, '', '이태인', 'tim', 1, 'timlee1027@gmail.com', '620713', '', '', '', '02--', '010--', 0, UNIX_TIMESTAMP('2012-09-04 12:08:52'), UNIX_TIMESTAMP('2012-09-04 12:08:52'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('walnut59', 'ftvpi8ubphofqeph', 2, '신길', '김현미', 'mimi59', 1, 'walnut59@hanmail.net', '5905092064133', '경기 화성시 안녕동 남수원현대아파트', '103-507', '445994', '031-223-0053', '010--', 0, UNIX_TIMESTAMP('2012-10-18 11:29:36'), UNIX_TIMESTAMP('2012-10-18 11:29:36'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('wany505', 'ftvpi7291tleph', 7, '김달회', '김지완', 'wany', 1, 'wany505@gmail.com', '8105051074419', '경기 용인시 기흥구 보정동', '1250-1번지 wany house 401호', '446858', '031-889-7838', '010-3781-7714', 0, UNIX_TIMESTAMP('2009-01-21 00:24:27'), UNIX_TIMESTAMP('2009-01-21 00:24:27'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('wmpkorea', 'ftvpi8118qnxeph', 7, '김창견', '김태한', '푸른소망', 3, 'ukrkim@gmail.com', '6508021018069', '경기 구리시 수택동', '270번지', '471030', '02--', '010-2245-5519', 0, UNIX_TIMESTAMP('2011-11-20 08:26:47'), UNIX_TIMESTAMP('2011-11-20 08:26:47'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('yjw8202', 'ftvpie115tpfeph', 0, 'DSLR', '윤정운', '운이™', 1, 'yjw8202@nate.com', '8202221047319', '서울 도봉구 도봉2동 한신아파트', '118동 1007호', '132731', '02-955-8008', '010-5137-0128', 0, UNIX_TIMESTAMP('2009-09-17 00:00:51'), UNIX_TIMESTAMP('2009-09-17 00:00:51'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('yongjunk', 'ftvpi:8:85499eph', 4, '브니엘', '김용준', '백곰', 1, 'yongjunk@hanmail.net', '', '서울 종로구 부암동', '36-1 KCCC', '110816', '070-7417-4748', '010-7938-1577', 0, UNIX_TIMESTAMP('2013-05-10 10:16:21'), UNIX_TIMESTAMP('2013-05-10 10:16:21'), 0);

INSERT INTO users
  (userId, `password`, passQuest, passAnswer, name, nick, userLv, email, jumin, address1, address2, zipcode, phone, mobile, msgOk, registDate, updateDate, LastLoginDate)
VALUES
  ('zzangkcok', 'ftvpi1412sieeph', 1, '1', '옥광주', '옥광주', 1, 'zzangkcok2@naver.com', '8810301095813', '서울 송파구 송파1동', '115번지 태원맨션 401호', '138851', '02-3434-2424', '010-8926-5929', 0, UNIX_TIMESTAMP('2012-11-20 15:58:27'), UNIX_TIMESTAMP('2012-11-20 15:58:27'), 0);

