INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (7, '한국교회레크리에이션선교협회', '서울 도봉구 방학1동 도봉구청', '상계역근처', '132701', '02001', '3인이상 / 5인이하 가족단위l 일시귀국 선교사 사용기간은 최장 2개월(사용기간 종료후 다른 신청자가 없을 경우 재연장 가능함) / 홈페이지에서 신청', 'lovehouse', '정진화', '', '011-278-3362', '--', '무료', 1, 1, '프린스하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (8, '서울장충교회 장근조장로 개인', '서울 강남구 역삼동', '609-1 리빙스톤', '', '02001', '세탁 / 주방시설 / 거실공동사용 / 방 4개 숙소이용기간 최대2달 / 리빙스톤 회사건물 1층을 선교관으로 사용하고 있음.', '', '사무실', '', '02-557-9035', '010--', '무료', 0, 0, '산돌하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.living-stone.co.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (10, '팀선교회', '서울시 은평구 불광2동 ', '산2번지 122-042', '', '02001', '한 가족이 3~4주 숙박가능', '', '(예약)', '', '02-355-1958 ', '02-359-8117', '무료 (예약금 25000원)', 0, 0, '한국기독교 수양관 (선교사의 집)', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (11, '축제교회 선교부', '서울시 성북구 동선동4가', '188번지 1층', '', '02001', '사용기간은 1개월 이내 / 사정이 있을 때에는 기간을 늘릴 수 있찌만 최대2개월을 넘길 수 없음. 싱글자매 선교사에 한해서 신청을 받음.', 'lovehouse', '서현정 전도사', '이기남 목사', '010-346-4493', '011-334-2192', '무료', 0, 0, '축제교회선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.jesusfestival.org', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (12, '제자교회', '서울 양천구 목동동로', ' 141-1 제자교회 8층', '', '02001', '간단한 양식 작성 후 담당교역자와 면담. 1개월 미만 단기숙소', '', '사무실', '', '02-2647-9090', '--', '무료', 0, 0, '목동제자교회', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://www.jeja.or.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (13, '빌라델피아선교회', '서울시 송파구 잠실6동', '7번지 장미아파트 상가 5층', '', '02001', '해외에서 활동중인 선교사는 1~3개월까지 숙박가능 / 사용신청서 / 파송증명서 / 단체장 추천서를 제출.', 'lovehouse', '사무실(8371~3)', '', '02-424-8371', '010--', '무료', 0, 0, '안식관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (15, '국제기아대책기구', '서울시 강남구 청담동', '111번지 기아대책', '', '02001', '사용10일전까지 국제개발원으로 예약신청', 'lovehouse', '사무실', '', '010-8724-9504', '010--', '유료 (1인 11000원 2인 14000원 3인 20000원)', 0, 0, '청삼선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.kfhi.or.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (17, '아현교회', '서울시 서대문구 충정로 3가', '35번지', '', '02001', '4인이 쓸 수 있는 방 4개가 준비되어있음. 숙소이용기간은 2주이나 담당자과 상담후 연장가능.', 'lovehouse', '사무실', '허미영', '02-312-0604', '02-364-6111', '유료 (1인:10000원식사제공)', 0, 0, '성결학사 게스트룸', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.haksa.org/main.htm', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (18, '장로회신학대학', '서울시 광진구 광장동', '353번지 장로회 신학대학내', '', '02001', '장신대교내 위치', 'lovehouse', '박현숙 간사', '', '02-450-5501', '02--', '유료', 0, 0, '장신대 세계교회협력센터', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (19, '온누리교회', '서울시 서초구 양재동', '55번지', '', '02001', '2인실 9개 / 12인실 6개 숙소이용기간은 최장 2주(주일과 공휴일엔 입실불가) / 전화는 받는것만 가능.', 'lovehouse', '이은옥 간사', '', '02-570-7504', '010--', '유료 (1일기준-2인실 44000원 12인실 132000원)', 0, 0, '횃불선교센타 숙소', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (20, '예장(통합)총회', '서울시 종로구 종로5가', '', '', '02001', '숙소이용기간 정해져 있지 않음. 이용료에 관리비가 포함되어있음. 전화 사용료는 따로 지불해야 함.', '', '사무실', '', '02-741-4370', '--', '유료 (1일기준 2인실 45000원 6인실 35000원)', 0, 0, '한국교회 100주년기념관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.pck100.co.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (21, 'YMCA', '서울시 종로구 종로2가', ' YMCA', '', '02001', '목회자할인혜택 / YMCA회원 10%할인', '', '사무실', '', '02-434-6884', '--', '유료 (1인실:55000원 2인실:70000원)', 0, 0, '종로YMCA호텔', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.YMCA.or.kr/hotel', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (22, '기독교 대한감리회 여선교회관', '서울시 한남동', '', '', '02001', '이불이 비치되어있음. 숙소이용기간없음.', '', '사무실', '', '02-790-6471', '--', '유료 (15인실:70000원 25인실:100000원)', 0, 0, '감리교 여선교회관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.kwscs.com', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (23, '', '서울시 강북구 수유동 ', '산67번지', '', '02001', '', '', '사무실', '', '02-993-6181', '--', '유료 (단체 : 방하나 90000원)', 0, 0, '호텔아카데미하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (25, '머릿돌교회', '서울시 광진구 자양동', '482-5', '', '02001', '', 'lovehouse', '사무실', '', '02-3436-1892', '010--', '무료', 0, 0, '게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (26, '지구촌교회 (조봉희목사)', '서울시 양천구 신정7동 ', '323-5', '', '02001', '숙소이용기간은 최장 6개월', '', '구내 (328/365)', '', '02-2647-0191 ', '--', '유료', 0, 0, '지구촌선교센터 선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.jiguchon21.com', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (27, '담당:조현섭집사', '서울시 강남구 수서동 ', '39번지 신동아아파트', '', '02001', '숙소이용기간은 2~3개월', '', '사무실', '', '02-409-7164 ', '011-9633-1110', '유료: 월 20만원 (관리비포함 )', 0, 0, '사랑수서선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (28, '담당:조현섭집사', '서울시 수서동', '', '', '02001', '(지하철 5호선 개농역 4번출구 5분거리)', '', '사무실', '', '02-409-7164 ', '02-448-0157', '유료: 1일 5천원 (관리비포함)', 0, 0, '사랑가락선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (29, '담당:조현섭집사', '서울시 송파구 오금동 ', '상아아파트', '', '02001', '', '', '(조현섭집사 직장) ', '(집)', '02-409-7164 ', '02-448-0157', '유료: 월 20만원 (관리비포함 )', 0, 0, '사랑 오금선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (30, '', '서울시 강남구 대치동 ', '은마아파트 ', '', '02001', '예약은 이메일로신청 willowlikely@godpeople.com', '', '', '', '', '--', '유료: 월30만원 (관리비포함)', 0, 0, '사랑 대치선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (31, '월간 한국인', '인천 남동구 구월2동', '70-66', '', '02015', '', 'lovehouse', '(서울사무실 : 박현정 / 유은하)', '', '02-2268-6636', '010--', '유료 (1일기준 4천원)', 0, 0, '선교사게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (32, '인천성광 선교센터', '인천 용현동', '', '', '02015', '전문인 선교 훈련시에는 조금 복잡할 수도 있음.', 'lovehouse', '사무실', '', '032-872-2336', '010--', '유료 (1인 3천원)', 0, 0, '게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (33, '선교중앙교회', '경기 성남시 중원구 상대원1동 ', '1411 4층', '', '02002', '온돌방 1개를 1개월간 사용가능 / 사전연락.', '', '사무실', '', '031-748-8291 ', '011-476-3551', '무료', 0, 0, '선교중앙교회 게스트룸', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (34, '', '경기도 가평군 경반리', '', '', '02002', '', '', '사무실', '', '031-581-6007', '--', '유료', 0, 0, '숭동기도원', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (35, '행신중앙교회', '경기도 금촌검산 ', '유승아파트 102동 203호', '', '02002', '임대아파트 1채를 국내에서 체류하는 모든 선교사들에게 개방', '', '사무실', '', '031-979-9191', '--', '무료', 0, 0, '행신중앙교회 게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (36, '총회세계선교회', '경기도 화성', '', '', '02002', '', 'lovehouse', '사무실', '', '031-354-5599', '010--', '유료 (1인 1일 2천원 식사1식 2천원)', 0, 0, '게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.gms.or.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (37, '기독교성결교단', '경기도 광주군 실촌면 곤지암리', '120-2', '', '02002', '* 홈페이지에 자세한 설명이 나옵니다(참조)

은혜의 동산 실촌 수양관에 오심을 환영합니다.
실촌이란 말은 열매 실(實) 마을 촌(寸)입니다.
즉 열매 맺는 마을이란 뜻입니다. 
신앙의 열매는 성령의 열매입니다. 
갈라디아서 5장에 나오는 사랑과 희락과 화평,
자비와 양선과 인내, 충성과 온유 절제의 열매입니다. 
누구든지 이 동산에 올라와 은혜 받고 성령의 
열매가 가득한 삶을 살아가도록 
하나님이 이곳을 허락해 주셨습니다.

실촌 수양관은 천호동교회 성도들의 영적 훈련뿐 만아니라 
전국의 성도들이 신앙훈련을 받은 자리로 자리매김하고 있습니다.
이곳을 찾는 성도 여러분!
마음껏 기도하시고 영성훈련을 통하여 
모세가 하나님을 만난 것 처럼 이 동산에서 
하나님을 만나시길 기원합니다. (아멘)', 'lovehouse', '사무실', '', '031-763-6631', '010--', '', 0, 0, '실촌 수양관', 4, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://sc.chonhodong.or.kr/', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (38, '', '경기도 양주군 장흥면 일영리 ', '산72', '', '02002', '', '', '사무실', '', '031-842-8011', '--', '유료 (1일 기준 4인-4만원)', 0, 0, '샬롬 유스호스텔', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (39, '', '경기도 광주', '', '', '02002', '', '', '사무실', '', '031-762-1350', '--', '무료', 0, 0, '기쁜 농어촌선교회', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (40, '', '강원도 속초', '', '', '02003', '', '', '사무실', '', '033-636-4530', '--', '유료', 0, 0, '추양선교재단안식관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (41, '예수제자운동(JDM)', '강원도 춘천', '', '', '02003', '', '', '사무실 (6701~4)', '', '033-243-6701', '--', '무료', 0, 0, '국제선교훈련원', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.jdm.or.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (42, '명성교회', '강원도 치악산', '', '', '02003', '운영시간:월요일 오전 10시~토요일 오후 3시까지', '', '사무실', '', '033-762-9998', '--', '유료', 0, 0, '치악산명성수양관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (43, '목포주안교회', '전남 목포시 산정동 ', '1671-3 목포주안교회 5층', '', '02007', '', '', '사무실', '', '061-272-4908', '--', '무료', 0, 0, '목포 주안교회 게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (44, '부전교회', '경남 울산시 울주군 웅촌면 검단리 ', '596번지', '', '02009', '', '', '사무실 (0558~9)', '', '052-268-0558', '--', '유료 (교역자(단체제외)는 6일까지 무료)', 0, 0, '부전 기도원', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (45, '마산 가포교회', '경남 마산시 가포동', '472-13번지', '', '02009', '', 'lovehouse', '(선교사관)', '(목사관)', '055-224-1457', '055-224-1455', '무료', 0, 0, '선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (46, '포항중앙침례교회', '경북 포항 남해도', '2-67', '', '02008', '', 'lovehouse', '사무실', '', '054-272-1126', '010--', '무료', 0, 0, '선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (47, '거제 염광교회', '경남 거제시 능포동', '660-13', '', '02009', '안식관 입주 희망자는 총회 선교부(02-596-5851)로 연락', 'lovehouse', '사무실', '(안식관)', '055-681-7611', '055-682-5100', '', 0, 0, '선교사 안식관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (48, '', '제주특별자치도 제주시 조천읍 와흘리 ', '산14-3', '', '02010', '', '', '사무실', '', '064-782-6969', '--', '유료', 0, 0, '이기풍선교기념관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.leekipoong.org', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (49, '', '서울', '', '', '02001', '이메일로 신청 yosej77@hanmail.net', '', '사무실', '', '011-780-0223', '--', '', 0, 0, '정요셉선교사', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (50, '', '경기도 포천군 소홀읍 직동리 ', '456번지 ', '', '02002', '', '', '사무실 (0515~8)', '', '031-544-0515', '--', '유료 (2~4인용 : 4만원 10인용: 9만원 20인용: 15만원(VAT별도)) ', 0, 0, '광림세미나하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.saintroom.co.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (53, '한국인선교사', '인천시 남동구 구월2동', '70-66', '', '02015', '규모 : 17평빌라 5개(각 방3개) 가전제품구비: TV, 냉장고 등
숙소별 전화번호 201호: 032-469-2224 
                       301호: 032-467-4397
                       302호: 032-467-2224
쉴터에 머물기를 원하시는 선교사님들께 부탁의 말씀을 드립니다.
쉴터에 예약을 하신 후 사정상 다른 숙소로 변경할 경우가 발생하면 저희에게 꼭 연락을 주시기 바랍니다.

* 2인기준에 추가 1인 : 1,000원
* 11월 ~ 4월 에는 겨울 난방비 : 12만원/월 추가
* 보증금 5만원 : 퇴실시 환불
* 요금은 월별 정산
******************** 홈페이지에서 신청(http://www.kormi.net/repose_03.html) ****************', '', '사무실', '', '032-471-2224', '010--', '1일 4천원(11~4월까지는 난방비로 한달 10만원 부담해야함)', 0, 0, '쉴터', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://www.kormi.net/repose_01.html', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (54, '성결교단 (담당: 조병철목사)', '인천시 서구 불로동 ', '416-4 수정선교센타 내', '', '02015', '3~9월까지 훈련기간에는 안식관에 빈 룸이 없음. 숙소 이용기간은 1달~3달까지', '', '사무실', '', '032-563-0509', '--', '유료(1일기준-원룸:8천원 투룸:12000원 쓰리룸: 15000원)', 0, 0, '기독교성결교회 선교사 훈련원 및 안식관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.omc.kehc.org', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (55, '한국인터서브', '서울시 서초구 반포4동', '551-6 샬롬빌 101호', '', '02001', '숙소이용기간은 최대 3개월

* 내용: 32평 빌라, 반지층, 방3, 넒은 거실, 화장실1, 주방, 가재도구완비 

* 사용료: 1일 15,000원 / 1개월 360,000원(전화요금 별도)

* 교통편: 고속버스터미널(3,7호선) 팔레스호텔 부근
', '', '박은옥', '', '070-7013-0085', '02--', '유료 (1일기준 15000원)', 0, 3, '샬롬빌', 2, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.intersk.org', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (56, '벧엘교회', '서울 영등포구 양평동3가', '78-19 5층(엘리베이터 없음)', '150103', '02001', '벧엘교회(예장합동)에서 운영하는 게스트하우스를 아래와 같이 안내드립니다. 
필요하신 분들께 도움이 되길 바랍니다. 


                                       ====   아 래   ===

① 사용자격: 초교파적 해외선교사
② 교회주소: 서울특별시 영등포구 양평동 3가 78-19 / 5층(엘리베이터없음)
③ 시설안내: 원룸형태 방 5개(각방 실평 약5평) 주방(공동취사) 세탁실구비
④ 게스트하우스 오시는 방법(교회약도: 첨부파일 참조)

    *지하철 2,5호선: 영등포구청역(3번)출구로 나와서 직진 건널목 건넌 후 동양웨딩홀 방면으로 직진 후 동양웨딩홀 끼고 우측으로 돌면 교회가 보입니다.

    *지하철 2,9호선 당산역(1번출구)로 나와 아울렛 방향으로 길을 건너신 후 동서울 정형외과 근처에서 마을버스 03번 탑승 종점에서 하차

    *자가용: 네비게이션에 교회주소를 입력하시면 됩니다.

⑤ 신청방법: 첨부파일(사용신청서)을 작성하여 교회메일 bdcv21@hanmail.net로 신청하시면 교회에서 담당간사님이 메일 확인 후 연락으로 접수가 완료됩니다.


<벧엘교회 문의 및 연락처>
☎ 사무실 : (02)2678-9940 (벧엘교회)   인터넷전화 : 070-7637-9940
  H P   : 011-208-6495 행정 담당 /  011-1787-9940 (담임목사) 
  E-mail: bdcv21@hanmail.net', 'lovehouse', '사무실', '', '02-2678-9940', '011-208-6495', '유료 (관리비포함 1만원~1만5천원)', 2, 5, '벧엘교회', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 1, 419, '벧엘교회_선교관_안내_및_사용신청서.hwp');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (58, '개인소유', '서울 도봉구 창4동', '181-46 플러스오피스텔 405호', '132905', '02001', '일반인은 25000원 / 관리비는 따로 지불
', 'lovehouse', '사무실', '', '010-8724-9504', '010--', '유료 (4인기준 1개월 : 300,000원 1일 : 20,000원)', 4, 1, '미션 홈 이프라임', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.cafe.naver.com/missionhome.cafe', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (59, '총회선교부 (GMS합동)', '서울 강남구 역삼동', '698-26', '135080', '02001', 'GMS 선릉힐은 서울시 강남구 역삼동에 위치하고 있습니다.
지하철 2호선 선릉역 부근이어서 교통이 편리하며 서울 본부와 가까운 거리에 자리잡고 있습니다. 
일시 귀국한 선교사들에게 실질적인 도움이 되도록 하겠습니다.

최장 1개월', '', '(행정국)', '', '02-568-9776', '010--', '10000', 2, 1, '선릉힐', 2, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://gmsad.gms.kr/?sec=604', 1, 448, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (60, '삼일교회 해외선교위원회', '부산시 동구 초량3동', '50번지', '', '02013', '초교파적으로 허용되나 삼일교회가 파송(후원)하는 선교사외는 소속 선교단체에서 선교사 신분확인필요', '', '사무실', '', '051-465-3131', '010--', '무료', 0, 0, '삼일교회 게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.samil.org', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (61, 'OMF선교회', '부산시 동구 수정동 ', '덕림아파트 351호', '', '02013', '1일~3개월까지 이용가능 / OMF회원 50%할인', '', '사무실', '', '051-751-5886', '016-570-3076 ', '유료 (1일기준 1만원)', 0, 0, '한국OMF선교회 선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.omf.or.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (62, 'GMS (총회선교부 합동)', '', '', '', '02013', '이용기간은 최대 4박5일 관리비(전기 / 수도) 따로 지불', '', '사무실', '', '051-621-5520', '011-9323-5520', '유료 (1일기준 2인용 2만원)', 0, 0, '메트로타워', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (63, '부산재송대교회', '부산시 해운대구 재송2동', '', '', '02013', '', '', '(교회)', '(추병호목사)', '051-784-1009', '017-846-2739', '무료(일주일까지) 1주일 이상은 연료비(가스전기)만 지불', 0, 0, '부산재송대교회 선교사게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (65, '삼흥교회 (합동) 남경기노회', '충남 공주시 유구읍 탑곡리', '161', '314894', '02005', '이 숙소는 안식년을 맞이하였거나 숙소가 필요하신 선교사님들을 위해 마련되었습니다. 

* 단체 수양관에서 생활해야합니다. 
* 숙소이용기간은 자유롭습니다. 
* 충남 공주시 유구읍 탑곡리 161-4
* 문의전화 02) 803-3288, 011-798-8222 
* 삼흥 수양관 041)841-8833 김명묵 목사
* 담당자 김명묵 목사

* 삼흥교회 주소 : 서울 금천구 시흥동 973-3', '', '사무실', '', '02-808-3377', '011-798-8222', '무료', 0, 6, '삼흥수양관', 4, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://samhoung.org/', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (66, '샘물교회', '경기 용인시 수지구 죽전동', '이지뷰 35동 301호', '448160', '02002', '? 개인신청보다는 선교단체의 추천을 통해 예약을 해주십시오. 
? 숙소이용기간은 최대 3개월입니다. 
? 선불 전화기와 선불 휴대폰이 준비되어 있습니다. 
담당자 서상희 집사
이메일 ksmns@yahoo.co.kr

홈페이지 www.smguesthouse.co.kr

운영기관 
주소 경기도 용인시 죽전동 이지뷰 35동 301호
교통편 지하철 분당선 오리역 도보로 5분 거리
약도-www.smguesthouse.co.kr', '', '서상희집사', '', '010-9209-5758', '010--', '유료 (1일기준 5천원(관리비포함))', 0, 0, '샘물게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.smguesthouse.co.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (67, '광명시청 기독신우회', '경기도 광명시 철산3동', '광명시청 앞 보보스텔', '', '02002', '* 3개의 룸이 있습니다.
너무 많은 분들이 신청하여 전화받기가 민망할 때가 있답니다. 
운영자들을 배려해 주시면 감사하겠습니다. 
이메일 문의 부탁드립니다.
kym000@kmc21.net

사용기간은 1개월 이내 / 사정이 있을 때에는 기간을 늘릴 수 있지만 최대2개월을 넘길 수 없음. 
선교단체나 교회에서 추천을 해야 입주가능.(구두추천가능)

문의전화 :  011-9933-6970
담  당 자 :  선교부장 김영민 권사
이  메 일 :  kym000@kmc21.net

주소 
교통편 인천공항에서 공항리무진(광명시 철산동 행)으로 1시간 10분 소요 
지하철: 7호선 철산역에서 도보 2-3분
약도- 광명시 철산3동 광명시청 앞 보보스텔', 'lovehouse', '김영민 권사', '', '011--', '010--', '5000', 0, 0, '선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (68, '', '경기 김포시 장기동 4차 ', '전원월드아파트 202동 103호', '', '02002', '방1칸을 1~2주간 사용.', '', '이상은사모) ', '(우강식목사)', '031-982-3644 ', '016-224-1958', '유료 (1~2인 1일 1만원 식사요청시 1식3000원)', 0, 0, '징검다리 하우스 (김포 선교사의 집)', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (69, '송파제일교회', '서울시 송파구 석촌동', '297-20', '', '02001', '15평형, 25평형 주방, 거실, 화장실, 이용기간제한없음', 'lovehouse', '사무실', '', '02-3432-0231', '--', '0', 4, 2, '송파제일교회 안식관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://www.songpa.or.kr', 0, 139, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (70, '오륜교회 (담당:이덕만목사)', '서울시 송파구 오륜동', '', '', '02001', '오륜교회에서 운영하는 게스트하우스 연립주택', '', '사무실', '', '02-402-0192', '', '', 0, 0, '오륜교회 선교사 게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (71, '국제 청소년센터', '서울 강서구 방화동', '801번지', '', '02001', '', 'lovehouse', '사무실', '', '02-2667-0535', '010--', '유료', 0, 0, '드림텔', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (72, '로뎀선교회 (담당:박명권목사)', '제주도 조천읍 선흥2리', ' 1799-2', '', '02010', '4개의 아파트식 선교관. 숙소이용기간은 1개월(연장가능 / 예약해야 함.) 선교사 신분 확인서와 교단소속증명서 필요', '', '사무실', '', '064-781-9050 ', '011-9850-2952', '무료', 0, 0, '로뎀선교회 해외선교사센터', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.rothemcenter.org', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (73, '추양선교재단', '강원도 속초시 설악동', '442번지 설악산 교회 앞', '', '02003', '한경직 목사님은,  우리 민족사에 있어서 가장 험난했던 수난,인고,격동의 한 세대를 살아 오시면서 일평생을 한결같이 절망 속에서 헤매는 젊은이들과 고아,과부등 불쌍한 이웃들을 예수 그리스도의 참사랑으로 돌보아 주시고 위로하여 주신 분이십니다. 믿음과 소망을 가지고 힘차게 살아갈 수 있도록 바른 길로 인도하시는 한편,오로지 이 민족의 영원히 축복받고 사는 길을 성경말씀으로 가르치시었습니다. 

  본 안식관은, 복음적 삶의 모범을 보여주신 그의 목회정신과 나라사랑,겨레사랑의 민족정신을 뜻있는 젊은 후진들이 배우고 뒤따르도록 하기 위한 곳입니다. 동시에 국내외에서 선교를 위해 애쓰시는 분들이 안식하며, 새로이 세계복음화를 향해 도전할 수 있는 영적인 힘을 재충전하기 위한 곳입니다. 활동에 대한 세미나와 자료교환을 하는 곳입니다.

* 온돌방   : 4실
   침대방(싱글2) : 7실

* 시설이용 하실분은 사용 15일 전까지 추양선교재단 사무국에 소정의 신청서를 제출하면 
본 재단에서 정한 "시설이용기준"에 따라 사용 7일 전까지 통보해 드립니다.

* 자세한 문의 : 서울 종로구 경운동 89-4 고합빌딩(별관 2층)
           (재)추양선교재단 (02)725-3664, (02)733-6564
', '', '사무실', '', '02-725-3664', '02-733-6564', '', 0, 11, '추양안식관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://kcm.co.kr/cymf/menu-sabbath.html', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (74, '임기매사장', '제주도 북제주군 조천읍 선홀리 ', '1925-2번지', '', '02010', '선교사 / 목회자들이 이용시 50%할인 / 주말이나 성수기에는 30%할인.', '', '사무실', '', '064-782-9000 ', '064-782-0272', '유료', 0, 0, '제주 황토마을', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.hwangtomaeul.com', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (75, '기독교 대한성결교회', '충남 조치원', '', '', '02005', '', 'lovehouse', '', '', '010-0-0', '010-0-0', '', 0, 0, '안디옥 해외선교회 선교센타', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.kehcnews.co.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (76, '복음천하교회 (담당: 김선희사무장)', '대전시 동구 천동 주공아파트', '', '', '02011', '선교사증명서 필요. 숙소이용기간은 2주.(일주일 전에 예약) / 1달이상 이용은 불가.', '', '(선교국) ', '', '042-533-3941', '010-5580-8320 ', '무료', 0, 0, '복음천하교회 게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.ggnc.or.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (77, '안산광림교회', '경기 안산시 단원구 고잔동', '632번지 안산광림교회 앞 빌라', '425020', '02002', '* 선교사 신분을 확인할 수 있는 증명서, 미션홈 사용신청서
* 신청방법
 - 안산광림교회로 1개월이전에 신청
 - 최장 1개월 체류가능
 - 입실시 교회사무실로 방문

* 문의 및 서류제출 : askl2@daum.net', 'lovehouse', '사무실', '', '031-484-3333', '011--', '무료', 6, 2, '안산광림교회 안식관', 2, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.askl.or.kr', 1, 420, '미션홈 사용신청서.hwp');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (80, 'GMS (총회선교부 합동)', '경기도 화성시 팔탄면 월문리', '110-1번지', '', '02002', '? 이 숙소 이용기간은 최대 3개월까지 이용 가능합니다. 
? 이 숙소는 수련회 장소로도 사용되고 있습니다. 
? 농구, 족구, 탁구를 할 수 있는 소체육관과 등산로와 산책로가 있습니다. 

*  2인용 : 6,000원 , 12평형, 초과시 1인당 1000원 추가
* 가족용 : 10,000원
* 문의전화 031)354-5599, 팩스: 031)354-8854 
* 이메일 : gmshq@gms.or.kr

* 교통편 : 사당역 4번출구에서 발안행 버스타고 발안 바다마트 하차
* 자가용 이용시: 서해안고속도로 발안IC로 나와 우측방향(조암), 삼거리에서 다시 우측방향(월문온천),
                       월문초등학교 지나서 우회전하면 선교센터가 보입니다.
', '', '사무실', '', '031-354-5599', '010--', '유료 (1일기준 2인용 6천원 가족용 1만원)', 0, 0, '총회 선교부(GMS) 바울관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 1, 453, '7갓러브하우스선교관신청서.hwp');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (81, '새중앙교회', '경기도 안양시 동안구 평촌동', '158-3번지 새중앙교회 내 4층', '', '02002', '새중앙교회 홈페이지에서 선교관 신청을 하시면 됩니다.

? 2인실 12개와 4인실 2개를 갖추고 있습니다. 식사도 무료로 제공됩니다. 
? 선교관 예약신청을 하셔야 하며, 이용 14일 전까지 확정된 일정을 보내주셔야 합니다. 
? 부대시설로 식당, 커피숍, 선교관휴게실, 공동세탁실이 있습니다. 



', 'lovehouse', '사무실', '', '031-420-8540', '010--', '무료', 0, 0, '새중앙교회', 4, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://www.sja.or.kr/spe/spe3_05_03.aspx', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (82, '사랑누리교회', '경기도 수원시 영통동 ', '황골마을 945-4 한솔프라자7층', '', '02002', '선교사 파송증명서 제출. 숙소이용기간은 3개월 / 연장가능', '', '사무실', '', '031-206-5479 ', '011-251-6689', '1일기준 5천원 ', 0, 0, '사랑누리교회', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.lovenuri.org', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (83, '개포감리교회', '서울시 강남구 서초동', '', '', '02001', '숙소이용기간은 1주일', 'lovehouse', '사무실', '', '02-2226-9220', '017-319-2359', '무료', 0, 0, '게스트하우스', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'www.kmc.or.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (84, '명성교회', '서울시 강동구 천호동', '', '', '02001', '타교단선교사는 선교부에 먼저 허락을 받아야 함.', '', '사무실', '(숙소)', '02-440-9058 ', '02-474-6900', '무료', 0, 0, '명성교회 안식관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://www.msch.or.kr', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (85, '아시안미션', '경기도 시흥시 월곶동', '1010-4 풍림아이원APT 110동 2001호 / 2004호', '', '02002', '이 선교관은 선교지에서 수고하시는 선교사님들의 휴식과 충전을 위해 이랜드 기업이 마련한 공간입니다.

*이용안내
 - 이용기간 : 6개월
 - 이용기준과 원칙 : 1) 아시아미션 협력기관 소속 및 후원 선교사
                            2) 한 텀(4년)이상의 사역을 마친 안식년 선교사
 - 신청 : 아시안 미션 홈페이지를 통해 예약신청하여 작성
 - 통보 : 신청서 접수 후 1주일 이내 개별통보
 - 신청 시 유의사항 : 희망 입주일 한달 전에는 신청하셔야 합니다.


 방  : 12평 원룸(주방딸린 큰방1, 목욕탕,전용베란다,  

 편의시설  : TV,세탁기,가스랜지,등 생활가전일체 
 
 비용 : 한달 10 만원 (신한 140-007-836313 사단법인아시안미션)  
 
 주건환경 : 시흥시 월곶동의 풍림아파트단지 상가단지가 인접, 각종 위락
  시설, 편의시설로 일상적 생활이 용이
  20층 두 원룸의 전망 매우 좋음(월곶포구) 
 
 교육시설 : 오이도역부근 함평초교, 함평중학교 개교 
', '', '사무실', '', '02-2012-5243', '02--', '100000/ 월', 4, 2, '월곶 선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', 'http://www.asianmission.or.kr/House/introduce.asp?Code=01', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (87, '아시안미션', '서울 서초구 서초동', '롯데캐슬 클래식아파트 104동', '137070', '02001', '이용기간: 6개월 이용기준 : 아시안미션 협력기관 소속 및 후원선교사 / 4년이상의 사역을 마친 안식년선교사 신청 : 희망 입주일 한달 전에 신청', '', '사무실', '', '02-2012-5243', '02-534-2303', '유료 (기간내 사용한 모든 관리비 및 공과금)', 0, 0, '아시안미션 서초선교관', 1, UNIX_TIMESTAMP('2008-12-29 22:48:19'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (91, '산유화펜션', '경남 산청군 단성면 방목리', '163-28', '666944', '02009', '<ul style="none">
<li>여름성수기(7월 15일에서 8월 30일까지)와 금~일은 사용할 수 없습니다.</li>
<li>펜션내 구비시설 : TV, 드라이기, 에어컨, 냉장고, 전기밥솥, 핫플레이트</li>
<li>방도구(그릇 및 수저), 원목식탁</li>
<li>세탁기 없음</li>
<li>제공 물품 : 휴지, 치약, 비누 [수건은 별도지참 ]</li>
<li>사용후 청소를 잘해주시기 바랍니다.^</li>
</ol>', 'jstruth', '김종수', '', '010-8591-6394', '--', '20000', 5, 2, '산유화 펜션', 4, UNIX_TIMESTAMP('2010-02-17 16:18:24'), 'S2001', 'http://www.suhps.com', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (94, '명성교회(안산)', '경기 안산시 단원구 고잔1동', '602-1번지', '425803', '02002', '* 먼저 전화나 매일로 문의하여 주시고 예약을 하신 후 일정에 맞추어서 이용하실 수 있습니다
* 방3개(침대방, 온돌방)와 거실, 욕실, TV, 에어컨, 인터넷 PC, 주방시설, 간단한 운동기구 등을 구비하고 있습니다.', '', '담당자', '', '031-482-5000', '010--', '무료', 5, 3, '명성교회(안산)', 2, UNIX_TIMESTAMP('2010-09-02 17:20:36'), 'S2001', 'http://www.ms21.or.kr/one_html/index.php?menu_id=149', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (95, '(고신)총회유지재단', '서울 서초구 반포4동', '58-10', '137803', '02001', '* (고신)총회회관에서 운영하는 회관입니다. 
- 강남고속버스터미널에서 가까운 곳에 위치하고 있습니다. 
- 객실은 2인실에서 10인실까지 있습니다. 가격은 20,000원~100,000원까지 있습니다. 
- 객실에 따라서 취사가능여부를 확인하시기 바랍니다.

* 오후 11시 이후 출입이 안됩니다.', 'lovehouse', '허윤', '', '02-533-8158', '010-363-6906', '40000', 10, 2, '고신총회회관', 4, UNIX_TIMESTAMP('2010-11-18 10:56:50'), 'S2001', '', 2, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (96, '예들쉼터', '서울 성동구 하왕십리동', '1050번지', '133020', '02001', '교    단 : 초교파
이 용 료 : 2인 기준 5천원, 1인 추가시 성인 2천원, 미취학 아동1 천원
          (김치, 쌀, 세탁세제, 휴지는 쉼터 무료 공급)
이용기간 : 최장 3개월

문의 : sjk2046@naver.com

* 가격이 저렴하여 항상 만원입니다. 
  공간이 넓어 겨울철 난방비가 많습니다. 
  아껴서 사용하면 좋겠습니다.', 'mnb2046', '이병곤', '', '010--', '010--', '5000', 4, 5, '예들쉼터', 1, UNIX_TIMESTAMP('2011-03-12 22:26:35'), 'S2001', '', 5, 434, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (97, '이름없는교회', '서울 강남구 역삼동', '723-29 4층', '135080', '02001', '* 이름없는 교회에서 운영하는 선교관입니다. 
   (선교사 가족을 우선적으로 예약해드립니다)
* 단기체류를 원하시는 분만 가능합니다. 

* 총4개의 방중에 사용할 수 있는 방갯수는 3개이며, 나머지는 목사님 집무실입니다.
* 큰방에만 화장실과 드레스룸이 있고, 다른 방은 공동 화장실을 사용해야 합니다.
* 선교관은 4층에 있습니다.(건물에는 엘리베이트가 없습니다.)
* 3층에는 교회에서 운영하는 도서관이 있습니다. 
* 1층에는 교회에서 운영하는 카페 비아지오가 있습니다.  

* 모든 이용 접수는 e-mail 예약으로 받고 있습니다.
  (반드시 성별을 기록해 주시기 바랍니다.)
* E-mail: leina.s2s@gmail.com
* 데스크탑 컴퓨터, 무선 인터넷, 세탁기, 냉장고 등을 사용 가능합니다.

<갓러브하우스 공지>
* 접근성이 용이하여 많은 분들이 신청하십니다.
* 예약이 많이 밀려 있는 상태이오니 문의는 이메일로 하심이 좋을 듯합니다.

  
', 'heeyeon86', '박희연 전도사', '', '070--', '010--', '무료', 0, 3, 'NCC 게스트하우스', 2, UNIX_TIMESTAMP('2011-11-14 19:15:48'), 'S2001', 'www.nameless.or.kr', 3, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (98, '동서산부인과', '서울 강남구 개포4동', '1184-9', '135961', '02001', '* 예수님 사랑과 주의 종들에 대한 섬김으로 평생 사시다가
   2009.8.20(88세) 돌아가신 최순옥 권사를 기념하며 자녀들이 오픈한 곳입니다. 
   동서산부인과 최경숙 원장님께서 귀한 섬김으로 운영되고 있습니다.  

* 운영안내
  사용료는 1인 5000원, 추가인원 1인당 3,000원
  최장입실 기간은 30일이며 그 이상 필요하실 경우 선교센터의 승인이 필요합니다. 
      
* 아래에 첨부한 제출서류를 다운받아 작성하시고 팩스번호(02-6085-9311)로 보내주십시요.
 
  문의 사항은 02-566-9311 로 문의하시기 바랍니다. 가능하시면 이메일(dongsuh316@hanmail.net)로 부탁드립니다. 

* 복층구조로 되어있습니다. 
  각층마다 부엌이 있어 취사가 가능합니다. 
  아랫층에는 온돌방이며 간이 침대도 사용가능합니다. 
  

', 'dongsuh316', '동서산부인과', '', '02--', '010--', '5000', 0, 4, 'Soon Choi Mission Home', 4, UNIX_TIMESTAMP('2011-12-05 15:32:14'), 'S2001', '', 4, 435, '2갓러브하우스선교관신청서.hwp');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (99, '국제다리선교회', '서울 성동구 행당동', '37-81', '133070', '02001', '* 방  갯 수 : 5개
* 자      격 : 해외에서 사역하시는 선교사와 이에 준하는 목회자
* 사용기간 : 연 1회 1개월이내
* 제출서류 : 선교사역을 증명하는 서류 1통 지참

* 입실날과 퇴실날까지를 계산하여 하나은행 383-910004-19504, 국제다리선교회로 사용료를 입금하신 후
   임용순 선교사(010-3072-1560, pastorglim@hotmail.com)에게 전화로 예약하면 됩니다.
  (단순히 문의만 하실 분께는 사정상 상세한 답변을 못할 수 있음을 양해 바랍니다.)

* 반드시 아래 홈페이지에 가셔서 주의사항을 숙지하시고 진행하시기 바랍니다.

<갓러스하우스 공지>
* 퇴임하신 선교사님께서 운영하시는 선교관 입니다.
* 겨울철에는 난방비가 많이 들고 침구류 빨래가 힘듭니다. 그러한 가운데서도 섬겨주시는 귀한 곳이니 이용하시는  선교사님께서는 서로의 마음을 헤아리는 지혜가 필요합니다. 
  

', 'lovehouse', '임용순', '', '02--', '070-4142-1560', '5000', 0, 0, 'IBM선교관', 2, UNIX_TIMESTAMP('2011-12-18 22:30:10'), 'S2001', 'http://cafe.daum.net/ibm300', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (100, '그리심빌리지', '경북 영덕군 남정면 부경리', '10-1', '766843', '02008', '영적 목마름으로 인하여 영적 충전하고싶은 선교사님!
어디론가 "존 버연" 처럼 길을 나서고 싶은 순례자의 마음은 없습니까?
이곳 영덕 장사의 작은 어촌에 있는 
선교사 게스트 하우스 "그리심 빌리지"로 오세요. 
선교사님의 안식을 도와 드립니다.

1. 예약신청은 반드시 카페 메뉴의 "게스트 하우스 예약하세요!" 란을 참고하셔서 인터넷으로만 예약이 가능합니다. 
2. 신청에 필요한 서류는(신청서,파송증명서.소속증명서) 확인이 필요합니다. 
3. 인터넷 접수만이 가능 합니다. (전화는 잘 받지 않습니다. 외부 활동과 작업에 많은 방해를 받습니다. 그러므로 전화로 접수는 받지 않으며 게스트 하우스에서 남기신 연락처로 연락을 드리도록 하겠습니다.) 

* 더욱 자세한 내용은 홈페이지로 가셔서 공지글과 내용을 자세히 확인하시기 바랍니다.
 
방문하실 때 선교 현지 사역지의 기념될 만한 것 중에 1개품을 헌물해 주시면 선교지와 선교사님을 위해 기도하고 기념으로 "선교사님 방문 기념코너"를 만들어 전시하고자 합니다.자세한 문의는 본 게시판에 남겨 주세요. 


*기도요청*
- 그리심 빌리지 선교사 게스트 하우스의 겨울나기에 대한 재정이 열리기를 기도합니다. 
  선교사님의 안식이 계속 이어지길 바라는 마음은 저희들이 더욱 간절합니다. 그리심 빌리지는 건물이(연건평 약 100평)조금 큰 편이라 그런지 기름이 한 달 소요되는 양이 약800~1200리터 (매월/120만원~150만원) 정도 듭니다. 기름을 넣어야 하는 기간은 10월부터 11월, 12월, 내년 3월 말까지 6개월 간 보일러가 가동되어야 한다는 것입니다. 약 6개월간의 유류 대에 대한 재정 금액이 6개월 동안, 약 900만원에서 1,000만원 소요 될 것으로 봅니다. 저희들만이 절약해서 사용하면 한 달에 약 300~400리터 정도 드는 것 같습니다. 이러한 사정으로 추운 날씨에 선교사님을 모실 수 있는 환경이 아니기에 기도를 부탁드립니다.
  저희의 사역은 여름 시즌에 이곳을 이용하시는 교회와 개인, 단체에서의 사용료를 받아 운영하고 있으나 겨울에는 그 비용을 감당하기가 매우 힘이 들 것 같습니다. 14개월 동안 개인적으로 지출된 운영비만 약 오천만원 정도 지출되었고 이제 재정적으로 많이 힘들게 되었습니다. 앞으로 사역을 위해 재정이 열리는 일을 겸하기를 권면하는 많은 분들의 조언도 듣고 있습니다. 그래서 여러 가지 권면의 말씀이나 아이디어도 구합니다. 이 사역은 우리 혼자의 일이 아니라 열방을 향한 선교사님과 그 가정에 귀히 사용되어지는 사역입니다. 이러한 사역이 출발점이 되어 이곳 작은 어촌이 선교사 마을로 선교사님의 쉼터가 되기를 바라는 아버지의 마음에 합당한 사역으로 세워져 가길 기도해 주시기 바랍니다.       

http://cafe.daum.net/gerizimvillage/FjeK/51

-그리심 빌리지 선교사 게스트 하우스에서-
', '', '최바울', '', '010--', '010--', '무료', 4, 0, '그리심빌리지', 4, UNIX_TIMESTAMP('2011-12-19 13:12:29'), 'S2001', 'http://cafe.daum.net/gerizimvillage/78l5/34', 1, -1, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (102, '바울선교회', '경기 양평군 용문면 화전리', '1154번지', '476842', '02002', '* 두나미스 선교관(단체) 이용 안내 
1. 예약 안내
    ◈ 예 약 처 : Tel)031-774-9605(양평선교관) 
                      fax)031-774-3203 HP)019-264-5744
                     e-mail: lcmf7204@hanmail.net
              선교관 주소: 경기도 양평군 용문면 화전리 1154번지 

 ◈ 사용시간 : 입실 기준 시간은 오후 2시이며, 퇴실은 오전 12시를 기준으로 합니다
                     (이용 시간은 조정 가능함).    

 ◈ 예 약 금 : 예약 신청 후 3일 내에 전체 예약금 5만~20만원을 예약금으로 예치해 주셔야 합니다. 
                   만약 예약금을 예치하지 않으실 경우 예약이 해지될 수 있습니다. 
               ※ 예약을 취소하실 경우 예약금은 반환되지 않습니다. 

◈ 입금계좌 : 농   협  506-01-156578(예금주: 이원배) 

◈ 예약변경 : 참석 인원, 사용 시설 등을 변경하실 경우 최소한 예약된 날짜의 
                   4일 전까지 통지해 주셔야 합니다. 
 
◈ 식      비 : 식사는 원칙적으로 사용 단체가 식당을 이용하여 자체적으로 취사하는 것으로 합니다. 
               
2. 이용자 수칙 
    ◉ 사용이 허락된 방과 시설 외에는 다른 시설을 허락 없이 사용할 수 없습니다. 
    ◉ 단체인 경우에는 관리 사무실과 원활한 의사소통을 위해 담당자를 선정해 주시기 바랍니다.
    ◉ 화장실, 샤워실, 식당 등 공공장소에서는 서로를 위하여 질서와 청결을 유지해 주시기 바랍니다.
    ◉ 세면이나 샤워하실 때 물을 절약하여 사용해 주시기 바랍니다.
    ◉ 7월과 8월에는 온수가 공급되지 않습니다.
    ◉ 인화성 물질(모기향, 촛불)은 반입할 수 없으며, 이로 인한 화재 발생 시에는 본 선교관은 책임을 
        지지 않습니다.
    ◉ 선교관 사용 중 시설물 파손, 오염 및 분실 시에는 배상해야 합니다.
    ◉10분 이상 방을 비울 때에는 소등하여 주시고 퇴실하실 때는 방의 열쇠를 반드시 
       반환하여 주시기 바랍니다.

3. 사용 가격표
 
◈ 선 교 관

  층                   호실명              호 수            수용인원           수 량            사 용 료(연중 동일)
 3층              방1칸실(1박)        301~306           3~4명                6                    1만5천원
 2층              방2칸실(1박)        201~206          9~12명                7                      5만원
 1층             주방/식당(1일)         104                80명                 1                 50인 이하: 5만원
                                                                                                              50~100인: 8만원
                                                                                                            100인 이상: 10만원

 4. 장기 거주 예약
    본 선교관을 다음과 같이 이용할 수 있다.
    소속 선교 단체의 추천을 받아 (4년 이상 해외선교) 본 선교관 운영위원회 심사를 거쳐 
    입주를 허가한다.

◎ 장기 거주자 입주 헌금은 룸 별로 다음과 같이 정한다.
      ① 원 룸 : 1,000만원
      ② 투 룸 : 2,000만원
 
    ※  입주 헌금은 중간에 나가실 때 또는 소천 시에는 선교관 사업에 헌납된다.
 
안식년 선교사는 다음과 같이 구분하여 사용료를 납입한다.
    ① 바울선교회 및 대륙복지회 선교사의 사용료는 무료이다.
    ② 타 단체 선교사는 원룸은 매일 3,000원, 투룸은 매일 6,000원이고 1~3개월까지 거주할 수 있다.
    ③ 해외 전화요금과 개인 용도 차량 연료비는  개인 부담으로 한다.
', '', '선교관사무실', '', '031-774-9605', '010-264-5744', '15000', 4, 6, '두나미스 선교관', 4, UNIX_TIMESTAMP('2011-12-28 18:11:33'), 'S2001', 'www.bauri.org/dunamis', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (103, 'God 1st Guesthouse', '서울 용산구 서계동', '238-53번지', '140830', '', '샬롬! 주님의 이름으로 환영합니다. 

세계 50여개국, 2000여명의 선교사들이 다녀가신 한국선의복지재단 크리스천 게스트하우스는 
지난 10여년간 이루 말할 수 없는 축복의 쉼터였습니다.
그러나 2010년 국가의 도시환경정비사업 시행으로 용산에 위치하던 게스트하우스 운영이 안타깝게 중단되었습니다.
게스트 하우스를 위해 기도하던 중 주의 종을 쉬지 말고 섬기라는 부르심에 순종하기로 결심하였고,
기도하던 중 마침내 2011년 4월 God 1st Guesthouse 개관으로 열매를 맺게 되었습니다.
주의 은혜로 문을 연 God 1st Guesthouse는 고국에서 숙소가 필요한 국내외 선교사들의 안식처로 사용되며,
선교사들의 사역에도 힘써 협력하여 세계비즈니스 선교사역의 비전을 이뤄나가겠습니다. 

* 온돌방1개(2만원), 2인실 침대방 1개(2만5천원), 가족이 머무를 수 있는방 2개(각각 3만원) 입니다.
* 각방 요금은 1인 기준이며, 별도로 1인 추가시 5천원 할증되고 2주 이상 숙박하시는 분들은 20% 할인 적용됩니다.

* 예약시 7일전까지 연락주셔야 합니다. 
* 홈페이지를 통해 예약하셔야 합니다.

담당자 이희원 간사, hw8157@hanmail.net
 
', '', '이희원 간사', '', '010-2224-8157', '010--', '30000', 4, 4, 'God 1st Guesthouse', 1, UNIX_TIMESTAMP('2012-02-05 21:30:10'), 'S2001', 'http://www.god1stguesthouse.or.kr', 1, -1, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (104, '국제쉼터선교회', '강원 고성군 간성읍 흘리', '22-3', '219804', '02003', '편안한 안식과 쉼과 휴식이 필요하신 선교사님, 목사님과 전도사님과 기독사역자의 가족은 무료콘도를 신청해 주세요.
 
 Jong Won Ko
 선교사님, 목사님과 전도사님과 기독 사역자의 가족을 위한 무료 콘도를 소개 해 드립니다.
 
 안식과 편안한 쉼이 필요하신 선교사님 가족과 목사님 가족 그리고 전도사님, 복음가수, 기독교화가, 기독교언론방송인 가족을 무료 콘도로 모시겠습니다. 

 무료로 이용하실 콘도는 70개 객실을 갖춘 강원도 알프스 리조텔 글로빌 콘도입니다.
 콘도 홈페이지 http://www.alpsps.com/ 

신청은 꼭 국제쉼터 선교회 임시 카페인 다음카페/안식관에서 신청을 해 주세요.
 http://cafe.daum.net/godrest
 
1. 주방기구는 다 구비되어 있습니다.
 2. 실내 바비큐장이 구비되어 있습니다.
 (현장에서 바베큐 식단을 사드실 분은 출발 하루전에 미리 신청해 주셔야 드실 수 있습니다)
 3. 성수기와 준성수기 그리고 주말을 제외한 비수기(1년중 250~300여일)에 이용하실 수 있습니다.
 4. 비수기때 주일 오후부터 금요일 오전까지 무료로 사용이 가능합니다.
 5. 콘도 한 개를 이용하실 수 있는 기본 인원이 4인 가족입니다.
 6. 무료 이용 제한 기한은 없습니다.
 7. 여러분 교회의 목사님 가족과 전도사님 가족의 건강과 안식과 쉼을 위해 무료 콘도를 전해 주세요.
 8. 공유하기 클릭하셔서 목회자님과 선교사님, 복음가수, 기독교화가, 기독교언론방송인 가족에게 편안한 안식과 휴식과 회복과 쉼을 선물 해 주세요..
 9. 알프스 글로빌 콘도를 운영하시면서 무료로 선득 제공해 주신 장로님(대학 교수님)을 위해 기도해 주세요(-.-)
 
 * 알프스글로빌콘도 홈페이지는 http://www.alpsps.co.kr/ 
 * 무료콘도 신청은 다음카페/안식관 http://cafe.daum.net/godrest 에서 해주세요..
 * 문의는 국제쉼터선교회 고종원간사(010-4751-9004. 070-8200-8089)', '', '고종원 간사', '', '010--', '010--', '무료', 0, 70, '알프스글로빌콘도', 4, UNIX_TIMESTAMP('2012-02-05 21:45:12'), 'S2001', 'http://www.alpsps.co.kr/', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (106, '삼광교회', '서울 동작구 사당1동', '1002-18', '156824', '02001', '♣ 삼광교회 선교사쉼터 

이 숙소는 한국에 단기체류하시는 선교사님들을 위한 숙소입니다. 

♣ 시설안내  (1일기준) 

*   구 분         - 이 용 료                   - 내    용                -기   타
   - 2 인실         *  5,000원(1인)         방1, 공동주방         냉장고, 세탁기, 전자렌지
   - 가족실        *10,000원                 방1, 공동주방

♣ 가족실 3개와 2인실 4개로 구성된 선교사 쉼터입니다. 

♣ 숙소이용기간은 최대 30일입니다. 

♣갓러브하우스 공지♣
 숙소이용은 이메일로 신청하셔야 합니다(전화하시면 섬기시는 분이 힘드십니다.)

♣ 자세한 내용은 평일에 연락바랍니다.

● 교회주소 : 서울특별시 동작구 사당로26길 18(사당1동 1002-18 삼광교회)
● 연락처 : Tel. 02) 597-2110 Fax. 02) 597-1135
● 홈페이지 : www.samkwang.or.kr
● 교통편 : 이수역 4,7호선 인근. 7호선 9번 출구 방향 100m 전방 삼광교회
● 제출서류와 제출처 : 사용신청서와 파송증명서,  jhyun1208@hanmail.net (최정현강도사 : 010-3594-1409)로제출

', 'lovehouse', '최정현 강도사', '', '02--', '010--', '무료', 0, 0, '쉼터', 1, UNIX_TIMESTAMP('2012-02-11 22:31:14'), 'S2001', 'www.samkwang.or.kr', 1, 308, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (109, '개인운영', '서울 영등포구 양평동3가', '90-1 거성파스텔 아파트 103동 501호', '150103', '02001', '* 선교관 전화: 02)2635-2151
* 문 의 전 화: 02) 719-0347/8/9
* 비상연락망: 010-4204-6050 
* 접수,E-mail: davidahome@naver.com

* 숙박
  저희 다비다의 집은 총 4개의 방이 있습니다.
  싱글 선교사님들  네 분이 동시에 묵으실 수 있으며,
  가족단위 선교사님과 싱글선교사님이 동시에 묵으 실 수도 있습니다.
  다만 공동 생활의 개념이다보니 싱글 선교사님만 묵게 되실 경우 
  같은 성별의 선교사님만 계실 수 있도록 배려해드리고있습니다.

* 월~금요일(9시~5시) 입실 가능하십니다. 
   선교관에 다른 선교사님이 계시는 경우에는 시간이 상관 없지만 
   안 계시는 경우에는 정해진 시간에 입실 하실 수 있도록 부탁드립니다.

   또한 토요일과 주일은 입실 불가하십니다. 양해 부탁 드립니다.
  
* 숙박료
   하루 이용료는 10,000원 입니다.
   인원과 관계없이 한 방 하루 투숙당 만원으로 계산됩니다.
  (영리추구를 위한 운영이 아니다보니 관리에 필요한 최소한의 비용으로 책정된 부분입니다.)
  
* 숙박료 정산
  퇴실시 선교관내 (거실 TV옆) 준비된 작은 헌금함에 넣어주시거나
  계좌이체해주시면 됩니다.  하나은행  이진희  179-014982-00107
  따로 관리자와 정산작업은 거치지않습니다.
  하나님의 마음으로 헌금해주세요.

  더 좋은 시설과 환경으로 선교사님들을 오랫동안 섬길 수 있도록 최선을 다하겠습니다.

* 기타
  - 개인 짐 보관은 어렵습니다. 상주하는 관리인이 없어 보관 및 관리에 위험이 있습니다.
  - 개인 음식물은 퇴실 시 모두 처리해주세요. 위생의 문제가 있습니다.
  - 함께 묵으시는 다른 선교사님께 피해가 되지않도록 함께 깨끗하고 조용한 공간을 만들어 주세요.  
  - 밤늦은 TV시청 및 소음은 쉼에 방해가 될 수 있습니다 ^^;;
  - 매달 24일은 도시가스 검침일입니다.
  - 세탁기가 있는 베란다에서 도시가스 계량기 숫자(검은색 부분 4자리 수)를
     현관문 옆 벽에 기입해주세요
  - 열쇠는 아파트 동 입구 출입카드와 현관문 열쇠 가 함께 있습니다. 
    가족단위 선교사님께는 2개, 싱글선교사님께는 1개를 드립니다. 

    분실에 주의해주세요^^
 
* 투숙할 수 있는 기간 : 최소 30일 이상
* 모든 이용 접수는 e-mail 예약으로 받고 있습니다.

   선교사님들의 많은 애용 부탁드립니다. ^＾



', 'lovehouse', '', '', '02-719-0347', '010-4204-6050', '10000', 0, 4, '다비다의 집', 1, UNIX_TIMESTAMP('2012-09-11 12:26:18'), 'S2001', 'http://blog.naver.com/davidahome', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (110, '갓러브하우스', '인천 부평구 삼산동', '377-7 보우하트빌리지 15동 101호', '403090', '02015', '가족이 머무시기에 좋습니다. 

문의는 godlovehouse@godlovehouse.net
빌라입니다.

가   격 : 방3곳 모두사용 15,000원 
관리비 : 따로 없습니다.
최장거주 : 3개월
', 'jhouse', '정진화', '', '010--', '010--', '15000', 0, 3, '갓러브하우스', 2, UNIX_TIMESTAMP('2012-09-12 18:20:16'), 'S2002', '', 3, 436, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (111, '한국인터서브', '서울 성동구 하왕십리동', '극동미라주 아파트 103동 501호', '133020', '02001', '* 내용: 29평 아파트, 5층, 방3, 넓은 거실, 화장실1, 주방, 가재도구완비 
* 사용료: 1일 15,000원 / 1개월 360,000원(전화요금 별도)
* 주소: 서울 성동구 상왕십리 극동 미라주 아파트 103동 501호
* 교통편: 2호선 신당역, 3호선 옥수역 (마을버스 하차) / 5호선 행당역(도보10분)
', '', '박은옥', '', '010--', '010--', '무료', 0, 3, '로고스관', 1, UNIX_TIMESTAMP('2012-09-21 17:01:25'), 'S2001', '', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (112, '한국인터서브', '경기 성남시 분당구 정자동', '75-3', '463874', '02002', '
* 내용: 17평 빌라, 2층, 방2, 부엌 겸 거실, 화장실1, 가재도구 완비
* 사용료: 1일 13,000원 / 1개월 300,000원
* 교통편: 분당선 정자역, 수내역(도보10분)', '', '', '', '070--', '010--', '무료', 0, 2, '벧엘관', 2, UNIX_TIMESTAMP('2012-09-21 17:40:08'), 'S2001', '', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (113, '한국 인터서브', '부산 영도구 영선동4가', '1106번지 동산아파트 801호', '606817', '02013', '* 내용: 38평 아파트, 8층, 방3, 넓은 거실, 화장실1, 과재도구 완비
* 사용료: 1일 15,000원/ 1개월 200,000원(아파트 관리비 별도, 단기는 지불안함)
* 교통편: 부산역에서 버스로 30분, 택시로 15분 거리

이메일: house@intersk.org
', '', '', '', '070--', '010--', '무료', 0, 3, '마므레홀', 1, UNIX_TIMESTAMP('2012-09-21 17:42:01'), 'S2001', 'www.intersk.org', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (115, '한국치과의료선교회', '', '', '', '', '', 'tabler74', '오요섭', '', '010-8478-7005', '010--', '무료', 0, 0, '한국치과의료선교회1', 1, UNIX_TIMESTAMP('2012-10-11 14:42:56'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (117, '사랑누리교회', '경기 수원시 권선구 세류2동', '1104-17', '441879', '02002', '♡선교관 이용안내

? 운영규정
1) 숙소 최대 사용기간은 90일입니다. (단, 30일씩 재연장 가능합니다.)
2) 입관 시 /입관 후 반드시 먼저 교회를 방문해 주세요. (간단한 오리엔테이션이 있습니다.) 
3) 퇴관하실 때 체크아웃 점검표를 작성해 주시고, 방명록을 기록해 주시기 바랍니다.
4) 퇴관 시 사용하신 방과 주방을 청소해 주시고 가져오신 물품은 모두 처리 해 주시기 바랍니다. 

  ?사용료 
1) 사용료는 1일 5,000원으로 하여 월별로 입금해주시면 됩니다. 
2) 드려진 헌금전액은 선교관 유지관리 및 선교관 건립을 위해 사용됩니다. 
    (※계좌번호: 신한은행 110-187-220410 이문범)

  ? 예약신청
1) 예약은 신청 근거를 남기기 위해 홈페이지와 이메일로만 받습니다. 전화신청 불가합니다.
2) 신청하실 때, 사용 희망기간을 알려주세요.
3) 성명과 인원, 소속 선교단체, 소속 교단 및 파송교회, E-mail, 전화번호를 남겨주십시오. 
3) 3개월 전부터 가예약이 가능하고, 입관 30일 전에 확답을 드립니다.   

* 교회 :   http://www.lovenuri.org
* 담당 : 김 승덕 전도사 /sunduk71@hanmail.net 
* 관리 : 노 재복 집사님 / 구현숙 권사님 
  (교회 직원이 아니라 봉사하시는 분들입니다. 정중하게 대하시기를 바랍니다.)

', 'jhouse', '교회', '', '031-206-5479', '010--', '5000', 0, 2, '사랑누리교회', 2, UNIX_TIMESTAMP('2012-10-12 12:19:09'), 'S2001', 'http://www.lovenuri.org', 1, 447, '5갓러브하우스선교관신청서.hwp');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (118, '국제복음선교회', '서울 송파구 송파1동', '144번지 선교회관 5층', '138852', '02001', '선교사 숙소
"할수 있거든 너희로서는 모든 사람으로 더불어 평화화라"(롬12:18) 

선교사 숙소에 오신 것을 환영합니다. 
이 숙소는 선교사님들이 한국에 계시는 동안 단기체류 할 수 있도록 지어져 운영되고 있으며, 
가족 숙소 1개와 독신 및 부부가사용할 수 있는 방 3개로 이루어져 있습니다.
엘리베이터가 없습니다.

 - 가족실(15,000원/일) : 방1, 욕실1, 공동주방
 - 2 인실(10,000원/일) : 방1, 욕실1, 공동주방


* 운영규정
- 입.퇴실은 근무시간에만 가능(오후 4시전)하며 부득이한 경우 미리 연락을 부탁드립니다. 
- 사용료는 입실과 함께 열쇠를 받으실 때 지불해 주시기 바랍니다. 
- 숙소 이용기간은 30일 이내입니다. 부득이한 경우에는 상담후 결정됩니다.
- 차를 가져오신 분은 차량앞 유리에 연락처와 "WEM 게스트하우스"를 기재해 주십시오.
- 개인실을 사용하시는 경우에는 주방에서 요리해 주시고, 공동주방이므로 다른 사용자를 베려해 주시기 바랍니다.
- 공동주방을 사용하는 경우에는 다른 가족과 함께 사용하시는 점을 감안하여 음식물 등을 남겨두지 마시고 깨끗이 청소하여 주세요. 
- 이곳은 선교사님들의 휴식을 위한 곳이므로 밤11:00부터 아침 6:30까지는 큰소를 내지 마시고 조용히 사용해 주세요. 
- 방안에 못을 박지 마시고 가구의 변경을 원하시면 WEM 선교회 간사에게 먼저 알려주세요.
- 인터넷은 유무선 모두 사용하실 수 있으며 070전화도 연결 가능합니다.
- 신청하시는 인원 이외에는 숙소에서 잠을 잘 수가 없으며, 다 아시겠지만 금연, 금주입니다. 
- 퇴실하실 때는 모든 음식물(냉장고 포함)은 치워주시고, 사용하신 방과 주방을 청소해 주세요. 
- 게스트하우스에 체류하시는 분은 WEM의 정기모임(격주 월요일 오후 7시)에 참석해 주시면 고맙겠습니다.

궁금사항이나 불편하신 사항은 WEM 사무실에(오전 9:30-17:30) 문의해 주시기 바랍니다. 
게스트하우스 연락처: 전화 (02)421-0888, 이메일: wem@wem.or.kr', '', '이용승', '', '02-421-0888', '010--', '10000', 5, 2, '게스트하우스', 1, UNIX_TIMESTAMP('2012-10-12 15:10:04'), 'S2001', 'http://www.wem.or.kr/new/sharing02.php', 1, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (121, '포곡제일교회', '경기 용인시 처인구 포곡읍 둔전리', '', '449812', '02002', '초등학교가 근처에 있고 사용기간 제한이 없어 어린 자녀를 두신 안식녁선교사님 가정이 사용하시기에 적합니다. 
자세한 내용은 아래를 참고해 주세요. 감사합니다.

1. 규모 : 24평형 빌라 1동 (방 3칸)
2. 시설 : 생활할 수 있는 시설이 거의 갖추어져 있음
         1) 냉장고, 컴퓨터(인터넷 가능), 드럼 세탁기, 정수기, 에어컨, TV  등
         2) 침대와 전화는 없음

3. 사용료 : 전혀 없음. 전기료, 수도료, 난방비 등은 본 교회에서 부담함.
4. 소재 와 운영 : 1) 경기도 용인시 처인구 포곡읍 둔전리 
                        2) 포곡제일교회에서 운영
5. 사용 방법 : 선착순 이며, 기간은 상담하시고 결정함.(전화, 메일 등)

6. 교통 및 주변 안내

    1) 공항 교통 : 용인 터미널에서 30분 간격으로 리무진 있음(인천공항, 김포공항)

    2) 일반 교통 : 안식관 앞에서 좌석 버스를 타면 강남 전철역까지 약 40분 소요됨

                         용인터미널에서 대구, 부산, 광주 등 직통 버스 있음

    3) 고속 도로 : 용인 톨게이트에서 1 km 거리에 안식관이 있음

    4) 교육시설 : (1) 도 서 관  : 2 km 거리에 포곡 도서관 있음

                  (2) 초등학교 : 안식관 바로 앞에 있음 (1-2분 거리)

    5) 편의시설 : 1 km 이내에 병원, 약국, 목욕탕, 서점, 마트 등이 있음

    6) 놀이시설 : 에버랜드, 캐리비안베이, 민속촌이 바로 인근에 있음.

7. 연락처 :  pj9184@hanmail.net', '', '사무실', '', '031-322-9182', '010--', '무료', 6, 3, '포곡제일교회 안식관', 2, UNIX_TIMESTAMP('2013-02-17 15:57:51'), 'S2001', '', 1, 454, '8갓러브하우스선교관신청서.hwp');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (123, '개인운영', '서울 성북구 동소문동1가', '133번지', '136031', '02001', '* 장로님 운영하시는 원룸입니다.
* 4호선 한성대 입구역에서 가까운 곳입니다.
  
* 비    용 : 처음 5일간 2만원, 6일째 부터 1만원 입니다. 
* 체류가능기간 : 1주일 이상 ~ 3개월 미만입니다. 
* 신청방법 :   chohjcho@hanmail.net

* 갓러브하우스 comment.
 ; 청결하고 좋은 곳입니다.
 ; 주변에는 창덕궁과 서울대병원이 가까이 있습니다.
 ; 운영하시는 분은 합동측 장로님 이십니다.', '', '조흥진 장로', '', '010--', '010--', '20000', 4, 1, '개인운영', 3, UNIX_TIMESTAMP('2013-03-01 13:06:45'), 'S2001', '', 1, 459, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (124, '개인운영', '경기 용인시 기흥구 영덕동', '1124-9 201호', '446908', '02002', '* 원천3교회 출석하시는 집사님께서 오픈하신 게스트하우스 입니다.
* 특별히 어려운 형편의 선교사님이면 좋겠다 하십니다.
* 새로지어져 깨끗합니다.

* 수원IC 부근입니다.

* 비    용 : 1만원 / 1일, 관리비 포함.
* 체류기간 : 1개월
* 신청방법 : 상기 첨부된 신청서를 작성하시어 u002002@naver.com, godlovehouse@nate.com 으로 신청', 'jhouse', '원천3교회', '', '010--', '010--', '무료', 4, 1, '수원게스트하우스', 3, UNIX_TIMESTAMP('2013-03-28 16:04:40'), 'S2002', '', 1, 478, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (125, '개인-한국침례회해외선교부소속', '서울 구로구 오류2동', '146-3번지 201호', '152896', '02001', '오류동 전철역  인근, 시장,  학교인접, 조용하고 깨끗한편임.
취사가능하지만 ,저희가정이 옆에 살고 있어서  
원하실 경우 식사 제공도 가능합니다.
MK(선교사님 자녀)사용가능합니다.
침례교단에  국한하지 않고 건전교단 소속선교사님은
선착순으로 사용가능합니다.
사용기간은 2개월에서 상의후 연장가능합니다.
', '', '배창숙, 박경우', '', '010-3601-8683', '--', '무료부터자율후원금', 3, 1, '연합 선교사님의 집', 2, UNIX_TIMESTAMP('2013-04-27 08:08:57'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (126, '선교사부부운영', '서울 구로구 오류2동', '146-3번지 201호', '152896', '02001', '오류동역과 생활편의시설, 병원들이 가까운 거리에 위치해 있습니다.
취사가능하고 깨끗하고 조용한 편입니다.
사용료는 사용하시는 선교사님들의 형편에 따라 자율적으로 받고자 합니다.
 2개월간 사용가능하시고, 연장 가능합니다.', '', '배창숙, 박경우', '', '010-3601-8683', '--', '', 2, 1, '소망선교관', 3, UNIX_TIMESTAMP('2013-05-09 11:04:50'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (127, '갓러브하우스', '서울 서초구 반포동', '727-3', '137040', '02001', '
* 갓러브하우스에서 위탁운영하는 곳입니다. 
  - 강남 지역에 상징적인 곳으로 운영하고 싶은 마음만 가졌었는데 이렇게 운영되게 되었습니다.
  - 많은 분들의 연합으로 이루어졌습니다. 
  - 이런 모델들이 많은 곳에서 이루어지길 또 기도해 봅니다.

* 사용목적 : 우선적으로 병원 치료목적으로 입국하시는 선교사님 우선입니다. 

* 사용비용 : 기본 1만원 입니다. 
          -  에어컨 사용이나 난방사용기간에는 추가비용을 받을 예정입니다. 

* 신청방법 : 신청서를 다운받아서 godlovehouse@nate.com 로 보내주세요.

* 문  의 :  반드시 이메일이나 문자로만 부탁드립니다.

* 후원자 : 권성훈(밥솥), 김난주(식기류), 김미화(전기주전자), 박경배(전자레인지), 
           WEC(냉장고 등), 갓러브하우스(싱글 침대 2개) 등
', 'jhouse', '정진화', '', '010-8591-6394', '010--', '1', 4, 1, '신논현 선교관', 2, UNIX_TIMESTAMP('2013-06-16 19:48:16'), 'S2002', '', 1, 488, '<a href=');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (128, '국제다리선교회', '서울 성동구 행당동', '37-81', '133070', '02001', 'http://cafe.naver.com/ibm300

왕십리, 한양대 역이 가깝습니다.
교통이 편리 합니다.
', '', '임용순선교사', '', '070-4142-1560', '--', '10000', 3, 4, 'IBM선교관', 3, UNIX_TIMESTAMP('2013-06-27 22:15:15'), 'S2001', '', 0, -1, '');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (129, '분당우리교회', '', '', '', '02002', '* 이용대상
 1. 분당우리교회 국내외 파송 및 동역 선교사(파송 1명, 동역선교사 70명(2012년 2월 현재)을 위한 공간으로
    위급한 상황을 제외하고 국내외 파송 및 동역 선교사만의 사용을 원칙으로 한다.

 2. 교회의 요청시와 공실이 발생할 경우에 절차에 따라 요청 선교사에게도 제공한다. 

 * 선교관 체류기간

 1. 파송선교사 30일
 2. 동역 및 협동선교사 15일을 원칙으로 하되 연장신청시 이후 예약상태에 따라 연장한다.
 3. 연장신청은 사용기간 종료 일주일 전을 원칙으로 하며 신청은 해외선교분과 사무실로 한다.(070-4345-7912)
 
* 선교관 현황 및 제공서비스
 1. 서현관/이매관/성지관 3개관
 2. 기본적인 생활비품 및 가전 제공
 3. 인터넷 및 인터넷 전화
 4. 기본적으로 선교관 사용료는 무료이며 식사는 제공되지 않습니다.

   단, 기본제공 외 발생비용(국제전화비 등)에 대해서는 사용자에게 청구할 수 있습니다.

   기타 자세한 문의사항은 선교분과 사무실(070-4345-7912)로 문의바랍니다.  

*  신청서 작성후 wpjoin@gmail.com 로 보내주시기 바랍니다.
   이용자격이 교회 파송선교사 우선입니다.
', '', '사무실', '', '070-4345-7912', '010--', '무료', 0, 0, '분당우리교회', 1, UNIX_TIMESTAMP('2013-07-03 09:28:49'), 'S2001', 'http://www.woorichurch.org/wch/s_board/download.asp?board_seq=262&board_sub_seq=1&view_sub_seq=0&filename=%BC%B1%B1%B3%BB%E7%C1%F6%BF%F8%BF%E4%C3%BB%BC%AD%2Ehwp&dir=0008790671_041', 0, 495, '사용신청서-분당우리교회.hwp');

INSERT INTO house
  (houseId, assocName, address1, address2, zipcode, regionCode, `explain`, userid, manager1, manager2, contact1, contact2, price, personLimit, roomLimit, houseName, buildingType, regDate, status, homepage, roomCount, documentId, document)
VALUES
  (130, '한국인선교사', '인천 남동구 구월동', '1457-1 메인프라자6층 이안오피스텔 55호', '405220', '02015', '안녕하세요?

인천 쉴터에 새로 마련된 게스트 하우스를 소개합니다. 

고시원와 오피스텔의 결합양식인  고시텔(원룸텔)이라 할 수 있습니다. 

이 게스트 하우스의 장점으로는 

1. 교통의 편리함: 인천버스 터미널, 인천 지하철( 인천예술회관역),롯데 및 신세계백화점 등 대중교통과 편의시설이 인접해 있어 편리한 부분들이 있습니다. 

2. 쾌적한 내부 - 시설이 오픈된지 얼마되지 않고 관리가 잘 되어있어 때문에 깨끗하고 미니냉장고, 에어컨 시설, 인터넷 사용이 원활합니다. 에어컨 등 냉방시설도 잘 되어 있으며 에어컨 비용은 사용료 안에 포함되어 있습니다. 

내부 시설로는 책상, 인터넷 모니터, 미니 냉장고, 가스대, 수납장이 있습니다. 

단 다소 규모가 좁은 공간이라 싱글 분이나 최대 두 분 정도 머물 수 있습니다. 창문이 없고, 주위에 방들이 밀접한 관계로 다소 소음이 있을 수도 있음을 말씀드립니다. 

', 'lovehouse', '최숙 간사', '', '02-2268-6636', '010--', '5000', 2, 1, '구월동 고시텔', 3, UNIX_TIMESTAMP('2013-08-08 00:03:50'), 'S2002', '', 1, 500, '<a href=');

