INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (1, -1, 'mission2', 'blackdew', '테스트 글쓰기 입니다.', UNIX_TIMESTAMP('2008-12-03 22:41:20'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (2, -1, 'mission2', 'blackdew', '글쓰기 두번째', UNIX_TIMESTAMP('2008-12-03 22:47:41'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (3, -1, 'mission2', 'blackdew', '글쓰면 들어갑니다.', UNIX_TIMESTAMP('2008-12-03 22:48:35'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (4, -1, 'mission2', 'lovehouse', '글아 쓰여져라', UNIX_TIMESTAMP('2008-12-06 03:21:48'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (5, -1, 'mission2', 'npngjjh', '안녕하세요.. 정진화입니다. 이렇게 한가족이 되어 넘 기뻐요.ㅎ', UNIX_TIMESTAMP('2008-12-19 16:26:00'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (6, -1, 'mission2', 'lovehouse', 'ㅇㅇㅇㄻㄴㅇㄻㄴㄹ', UNIX_TIMESTAMP('2008-12-30 00:07:31'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (7, -1, 'mission2', 'lovehouse', 'ㅇㄹㅇㄹㅇㄹㅇㄹㅇㄹㅇ', UNIX_TIMESTAMP('2008-12-30 00:07:36'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (8, -1, 'mission2', 'lovehouse', 'ㅇㄹㅇㄹㅇㄹㅇ', UNIX_TIMESTAMP('2008-12-30 00:07:39'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (9, -1, '1test', 'lovehouse', 'test', UNIX_TIMESTAMP('2009-10-29 23:21:29'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (10, -1, '1test', 'lovehouse', 'test2', UNIX_TIMESTAMP('2009-10-29 23:21:37'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (11, -1, '1test', 'lovehouse', 'test', UNIX_TIMESTAMP('2009-10-29 23:21:57'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (12, -1, '1test', 'lovehouse', 'ㄴㄴㄴ', UNIX_TIMESTAMP('2009-10-31 18:18:24'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (13, -1, 'mission2', 'lovehouse', 'aaaa', UNIX_TIMESTAMP('2009-11-01 20:10:09'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (14, -1, '1test', 'blackdew', 'test', UNIX_TIMESTAMP('2009-11-22 10:25:07'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (15, -1, '1test', 'lovehouse', 'test', UNIX_TIMESTAMP('2009-11-26 21:28:10'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (16, -1, '1test', 'lovehouse', 'test', UNIX_TIMESTAMP('2009-11-26 21:28:17'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (17, -1, '1test', 'lovehouse', 'test', UNIX_TIMESTAMP('2009-11-28 11:28:58'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (18, -1, '1test', 'lovehouse', '', UNIX_TIMESTAMP('2009-11-28 18:24:30'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (19, -1, 'mission2', 'lovehouse', '', UNIX_TIMESTAMP('2009-11-28 18:25:11'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (20, -1, '1test', 'lovehouse', '', UNIX_TIMESTAMP('2009-11-29 23:01:59'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (21, -1, '1test', 'lovehouse', '', UNIX_TIMESTAMP('2009-11-29 23:01:59'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (22, -1, '1test', 'lovehouse', '안녕하세요', UNIX_TIMESTAMP('2009-11-29 23:05:52'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (23, -1, '1test', 'lovehouse', 'ㅁㄴㅇㄹ', UNIX_TIMESTAMP('2009-11-29 23:22:50'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (24, -1, '1test', 'lovehouse', 'ㅁㄴㅇㄹ', UNIX_TIMESTAMP('2009-11-29 23:22:54'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (25, -1, '1test', 'lovehouse', 'ㅁㄴㅇㄹ', UNIX_TIMESTAMP('2009-11-29 23:23:12'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (26, -1, '1test', 'lovehouse', '테스트입니다.ㅎㅎㅎㅎㅎ', UNIX_TIMESTAMP('2009-11-29 23:23:38'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (27, -1, '1test', 'lovehouse', '테스트입니다. 테스트 수정 두번째', UNIX_TIMESTAMP('2009-11-29 23:23:47'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (28, -1, '1test', 'lovehouse', '테스트입니다.수정', UNIX_TIMESTAMP('2009-11-29 23:51:14'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (29, -1, '1test', 'lovehouse', '오늘의 테스트', UNIX_TIMESTAMP('2009-11-29 23:38:04'), 0);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (30, -1, '1test', 'lovehouse', '답글 테스트', UNIX_TIMESTAMP('2009-11-29 23:52:16'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (32, -1, '1test', 'lovehouse', 'ddd', UNIX_TIMESTAMP('2009-12-01 02:21:27'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (34, 32, '1test', 'lovehouse', '테스트 하나더', UNIX_TIMESTAMP('2009-12-06 21:07:02'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (36, 25, '1test', 'lovehouse', '테스트입뉘다', UNIX_TIMESTAMP('2009-12-06 21:11:23'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (37, -1, '1test', 'lovehouse', '댓클 추가하기', UNIX_TIMESTAMP('2010-01-23 22:02:45'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (38, -1, '1test', 'gebachoi', '오늘도 테스트를 합니다..ㅋㅋ', UNIX_TIMESTAMP('2010-02-06 19:00:23'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (39, 38, '1test', 'lovehouse', '감사하고 감사합니당 ^^', UNIX_TIMESTAMP('2010-02-18 00:14:51'), 1);

INSERT INTO familyComment
  (id, parentId, hostuserid, followId, comments, regDate, secret)
VALUES
  (54, -1, 'myanmagape', 'lovehouse', '귀한 사역에 위로부터오는 위로가 많으면 좋겠습니다.', UNIX_TIMESTAMP('2011-11-14 22:56:48'), 1);

