INSERT INTO code
  (id, code, name, type)
VALUES
  (6, '02001', '서울', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (7, '02002', '경기', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (8, '02003', '강원', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (9, '02004', '충북', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (11, '02005', '충남', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (12, '02006', '전북', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (13, '02007', '전남', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (14, '02008', '경북', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (15, '02009', '경남', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (16, '02010', '제주', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (17, '02011', '대전', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (18, '02012', '대구', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (19, '02013', '부산', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (20, '02014', '광주', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (21, '02015', '인천', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (22, '02016', '울산', '지역코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (23, '03001', '특별후원', '후원타입');

INSERT INTO code
  (id, code, name, type)
VALUES
  (24, '03002', '센터후원', '후원타입');

INSERT INTO code
  (id, code, name, type)
VALUES
  (25, '03003', '자원봉사', '후원타입');

INSERT INTO code
  (id, code, name, type)
VALUES
  (27, 'S1001', '진행중', '상태코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (28, 'S1002', '완료', '상태코드');

INSERT INTO code
  (id, code, name, type)
VALUES
  (31, 'S2001', '대기중', '상태코드2');

INSERT INTO code
  (id, code, name, type)
VALUES
  (32, 'S2002', '승인', '상태코드2');

INSERT INTO code
  (id, code, name, type)
VALUES
  (35, '01999', '기타', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (38, '002', '산업은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (39, '003', '기업은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (40, '004', '국민은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (41, '005', '외환은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (42, '007', '수협', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (43, '011', '농협중앙회', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (44, '012', '농협(회원조합)', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (45, '020', '우리은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (46, '023', 'SC제일은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (47, '027', '한국시티은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (48, '031', '대구은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (49, '032', '부산은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (50, '034', '광주은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (51, '035', '제주은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (52, '037', '전북은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (53, '039', '경남은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (54, '045', '새마을금고', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (55, '048', '신용협동조합', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (56, '050', '상호저축은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (57, '054', 'HSBC은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (58, '071', '우체국', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (59, '081', '하나은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (60, '088', '신한은행', 'BANK');

INSERT INTO code
  (id, code, name, type)
VALUES
  (63, '01998', '본부', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (64, 'S2003', '삭제', '상태코드2');

INSERT INTO code
  (id, code, name, type)
VALUES
  (67, '01008', '비공개', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (68, '01101', '감비아', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (69, '01102', '남아공', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (70, '01103', '마다카스카르', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (71, '01104', '모로코', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (72, '01105', '보츠나와', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (73, '01106', '우간다', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (74, '01107', '이디오피아', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (75, '01108', '세네갈', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (76, '01109', '씨에라리온', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (77, '01110', '카메룬', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (78, '01111', '코트디부아르', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (79, '01112', '케냐', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (80, '01113', '탄자니아', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (81, '01201', '네팔', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (82, '01202', '대한민국', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (83, '01203', '라오스', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (84, '01204', '러시아', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (85, '01205', '말레이시아', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (86, '01206', '몽골', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (87, '01207', '미얀마', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (88, '01208', '방글라데시', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (89, '01209', '베트남', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (90, '01210', '북한', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (91, '01211', '스리랑카', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (92, '01212', '아제르바이잔', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (93, '01213', '아프카니스탄', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (94, '01214', '우즈베키스탄', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (95, '01215', '이란', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (96, '01216', '인도', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (97, '01217', '미조람', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (98, '01218', '첸나이', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (99, '01219', '켈커타', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (100, '01220', '뱅갈로르', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (101, '01221', '인도네시아', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (102, '01222', '일본', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (103, '01223', '중국', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (104, '01224', '카자흐스탄', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (105, '01225', '캄보디아', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (106, '01226', '키르키스탄', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (107, '01227', '타직키스탄', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (108, '01228', '태국', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (109, '01229', '투루크메니스탄', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (110, '01230', '파키스탄', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (111, '01231', '파푸아뉴기니', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (112, '01232', '필리핀', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (113, '01301', '에콰도르', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (114, '01302', '캐나다', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (115, '01303', '도미니카', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (116, '01304', '미국', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (117, '01305', '아르헨티나', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (118, '01306', '파라과이', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (119, '01307', '멕시코', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (120, '01308', '페루', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (121, '01309', '브라질', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (122, '01310', '칠레', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (123, '01401', '팔레스타인', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (124, '01402', '이라크', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (125, '01403', '터키', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (126, '01404', '이스라엘', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (127, '01405', '이란', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (128, '01406', '요르단', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (129, '01501', '파푸아뉴기니', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (130, '01502', '뉴질랜드', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (131, '01503', '호주', '선교지');

INSERT INTO code
  (id, code, name, type)
VALUES
  (132, '01407', '알바니아', '선교지');

