INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (1, '복리후생 지원', '- 건강검진비와 의료비 지원
- 국내 체류비 지원
- 선교물품 구입비 지원
', '03002', UNIX_TIMESTAMP('2008-12-01 22:28:08'), 123);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (3, '상담 지원', '* 사역, 자녀 교육, 진학 등 전문적인 상담이 가능한 분의 지원이 필요합니다.', '03003', UNIX_TIMESTAMP('2008-12-01 22:34:24'), 132);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (4, 'IT 관련 지원', '- 홈페이지 유지, 보수 등에 은사를 가진 분
- 기타 컴퓨터, 인터넷 관련 상담이 가능한 분
- 사용하지 않는 컴퓨터를 단기간 빌려주실 분', '03003', UNIX_TIMESTAMP('2008-12-02 22:02:15'), 131);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (5, '차량 지원', '* 예사랑선교사케어센터(http://www.micace.net)에서 
  공항 픽업을 해드립니다. 
  홈페이지에 가셔서 신청하시기 바랍니다. 
', '03003', UNIX_TIMESTAMP('2008-12-02 22:02:27'), 130);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (7, '선교우편물 서비스', '* 예사랑선교사케어센터(http://www.micace.net)에서 
  선교우편물 서비스를 해드립니다.
  국내에서 선교사님의 선교편지를 이메일로 받아 그 내용을 인쇄하여 국내에서 선교사님이 원하시는 후원자에게 선교사님 대신 우편물을 발송하는 업무를 해 드리는 것입니다. 
  해외에서 보내는 것보다 국내에서 발송하므로 우편발송이 정확하고 짧은 기간내에 편지를 보내드릴 수 있어 발송시간이 절약되고, 국내우편이므로 발송에 따른 발송비용이 절감됩니다.
', '03003', UNIX_TIMESTAMP('2009-01-26 22:12:06'), 129);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (10, '핸드폰 무료 서비스', '* 예사랑선교사케어센터(http://www.micace.net)에서 
  핸드폰 무료 제공서비스를 해드립니다. 
  홈페이지에 가셔서 신청하시기 바랍니다.', '03003', UNIX_TIMESTAMP('2009-09-08 09:49:13'), 133);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (11, 'MK 지원', '* 선교사 자녀에게 레슨이나 학업 지도가 가능한 분
- 음악, 미술 레슨
- 학업 지도
- 언어 지도
- 체육 특기 지도', '03003', UNIX_TIMESTAMP('2009-09-18 15:59:18'), 126);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (12, '선교 행정비 지원', '- 물류와 통신비
- 소모품비
- 지급수수료(금융, 용역 등)
- 세금과 공과
- 관리비', '03002', UNIX_TIMESTAMP('2009-09-18 23:34:53'), 121);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (58, '결연 지원', '* 위기상황에 놓인 선교사님을 우선적으로 결연하여 드립니다.
   - 후원금 지원
   - 물품 지원
', '03002', UNIX_TIMESTAMP('2010-03-06 18:13:11'), 156);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (59, '은퇴선교사 지원', '* 은퇴하신 선교사님께서 상주하여 다음세대 선교사와 성도들을 위한 영적 유산을 
  전수할 수 있는 곳을 마련하고자 합니다.
   - 주택마련 자금 후원
   - 연금 조성을 위한 후원
', '03002', UNIX_TIMESTAMP('2010-03-06 18:19:27'), 144);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (60, '장학사업 지원', '* 아름다운 청년 장학금 입니다(함께했던 멋진 친구를 기리며...) 
  - MK(선교사 자녀)에 대한 학자금 지원
  - 선교지 아이들에 대한 학용품과 학자금 지원
', '03002', UNIX_TIMESTAMP('2010-03-06 18:22:46'), 145);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (61, '예비선교사 지원', '- 선교지 방문 및 기타 제 경비를 지원
- 선교후보생 훈련비 지원', '03002', UNIX_TIMESTAMP('2010-03-06 18:24:57'), 146);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (66, '청소 지원', '* 센터에서 관리하는 선교관 청소를 함께 하실 분', '03003', UNIX_TIMESTAMP('2010-05-04 12:06:49'), 155);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (67, '일반후원', '갓러브하우스에서 우선순위에 따른 긴급자금으로 사용됩니다.

- 선교사역의 긴급자금
- 센터사역의 긴급자금
', '03002', '2010-05-16 23:48:43', 157);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (68, '[터키]물품과 기기 지원', '- 디야르바크르에서 사역하시는 *** 선교사님께서 요청하신 물품입니다.
', '03001', UNIX_TIMESTAMP('2010-07-06 15:47:16'), -1);

INSERT INTO requestInfo
  (reqId, title, `explain`, supportType, regDate, imageId)
VALUES
  (69, '특별후원을 요청합니다.-테스트중', '테스트입니다.', '03001', UNIX_TIMESTAMP('2011-12-22 00:53:07'), -1);

