INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (1, 17, '축구공', '1개 5000 X 2개', 10000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (2, 17, '유니폼', '1개 5000 X 2개', 10000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (3, 17, '새로추가', '추가된 아이템', 100000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (4, 17, '추가2', '추가된 아이템', 30000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (5, 17, '추가2', '추가된 아이템', 30000, 'npngjjh', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (6, 18, '추가된 항목1', '컴퓨터', 400000, '', 'S1001');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (7, 18, '프린트', '프린터기', 100000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (8, 18, '책상', '컴퓨터 책상', 50000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (9, 19, '기타', '기타', 100000, '', 'S1001');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (10, 20, '자동차구입', '자동차 구입', 500000, '', 'S1001');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (11, 20, '자동차구입', '자동차구입', 100000, '', 'S1001');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (12, 20, '자동차구입', '자동차구입', 200000, '', 'S1001');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (13, 20, '자동차구입', '자동차구입', 1000000, '', 'S1001');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (14, 20, '자동차구입', '자동차구입', 100000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (15, 20, '자동차구입', '자동차구입', 100000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (16, 20, '자동차구입', '자동차구입', 8000000, 'glh811', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (17, 19, '기타', '기타구입', 100000, '', 'S1001');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (18, 19, '드럼', '드럼', 300000, '', 'S1001');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (19, 19, '피아노', '피아노', 1000000, 'glh811', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (23, 57, '침구류#1', '침구류가 필요합니다.', 50000, 'glh811', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (24, 57, '침구류#2', '침구류가 필요합니다.', 50000, 'glh811', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (25, 57, '침구류#3', '침구류가 필요합니다', 50000, 'glh811', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (26, 57, '취사도구#1', '취사도구가 필요합니다', 30000, 'glh811', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (27, 57, '취사도구#2', '취사도구가 필요합니다.', 50000, 'glh811', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (28, 57, '취사도구#3', '취사도구가 필요합니다.', 100000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (29, 57, '기타물품#1', '그외 기타물품구입비', 20000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (30, 57, '기타물품#2', '그외 기타물품구입비', 30000, 'lovehouse', 'S1002');

INSERT INTO requestItem
  (reqItemId, reqId, item, descript, cost, userid, sendStatus)
VALUES
  (31, 74, 'T', 'T', 100, '', 'S1001');

