INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (3, 'lovehouse', 320000, '03002', 'S2002', '정진화', '7210091889710', '070-7807-6394', '010-8591-6394', 'godlovehouse@nate.com', '463861', '경기 성남시 분당구 구미동 분당포스빌오피스텔', '434호', UNIX_TIMESTAMP('2009-10-22 00:12:51'));

INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (4, 'blackdew', 60000, '03002', 'S2002', '이숙번', '1111111111111', '02-111-11', '010-111-111', '111@111', '437822', '경기 의왕시 오전동', '1111', UNIX_TIMESTAMP('2009-10-22 01:18:32'));

INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (5, 'lovehouse', 0, '03003', 'S2001', '정진화', '7210090000001', '02-000-0000', '010-8591-6394', 'godlovehouse@gmail.com', '435743', '경기 군포시 산본2동 럭키백합아파트', '1125동 1302호', UNIX_TIMESTAMP('2009-12-10 22:09:14'));

INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (6, 'lovehouse', 330000, '03001', 'S2002', '관리자', '0000000000001', '02-000-000', '010-8591-6394', 'godlovehouse@gmail.com', '135520', '서울 강남구 수서동 까치마을아파트', '701동 805호', UNIX_TIMESTAMP('2010-03-03 22:47:05'));

INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (8, 'glh811', 0, '03001', 'S2001', '정진화', '7210091889710', '02--', '010-8591-6394', 'npngjjh@nate.com', '435760', '경기 군포시 오금동 한라2차아파트', '412동 1602호', UNIX_TIMESTAMP('2010-04-01 22:35:31'));

INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (9, 'glh811', 0, '03003', 'S2001', '정진화', '7210091889710', '02--', '010-8591-6394', 'npngjjh@nate.com', '435760', '경기 군포시 오금동 한라2차아파트', '412동 1602호', UNIX_TIMESTAMP('2010-04-01 22:42:43'));

INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (10, 'blackdew', 0, '03003', 'S2001', '이숙번', '7902271011215', '070-8118-6800', '010-8724-9504', 'blackdew7@gmail.com', '135782', '서울 강남구 수서동 신동아아파트', '701동 805호', UNIX_TIMESTAMP('2010-04-06 23:03:27'));

INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (11, 'luvtravis', 0, '03003', 'S2001', '임혜원', '8201032075032', '02--', '010-7321-0103', 'hyewonny0103@gmail.com', '437010', '경기 의왕시 고천동', '517 영광A 307호', UNIX_TIMESTAMP('2010-05-07 08:50:36'));

INSERT INTO supportInfo
  (supId, userid, sumPrice, supportType, status, name, jumin, phone, mobile, email, zipcode, address1, address2, regDate)
VALUES
  (12, 'mexicanspicy', 0, '03003', 'S2001', '정우영', '8307191121711', '02--', '010-4814-6788', 'mexicanspicy@naver.com', '135080', '서울 강남구 역삼동', '637-42 402호', UNIX_TIMESTAMP('2011-11-16 17:28:38'));

