INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (24, '능소화', 6, '', '불가', '가능', '불가', 20000, '91', '', 19, 34, 49, 64);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (27, '게스트하우스', 4, '', '가능', '가능', '가능', 0, '94', '', 184, 185, 186, 187);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (28, '4층', 10, '', '가능', '가능', '가능', 30000, '95', '', 386, 387, 388, 389);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (30, '큰방', 4, '', '무선', '가능', '가능', 0, '97', '', 202, 203, 204, 214);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (31, '2층침대방', 0, '', '무선', '가능', '가능', 0, '97', '', 206, 207, 208, 209);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (32, '작은방', 0, '', '무선', '가능', '가능', 0, '97', '', 210, 211, 212, 213);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (33, '소망2', 1, '', '', '가능', '가능', 5000, '98', '', 217, 296, 219, 297);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (34, '믿음방', 4, '', '', '가능', '가능', 5000, '98', '', 293, 294, 224, 295);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (35, '1인실', 1, '', '가능', '가능', '가능', 5000, '99', '', 226, 227, 228, 229);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (36, '에덴룸', 4, '', '', '가능', '가능', 0, '100', '', 231, 232, 233, 234);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (37, '', 4, '', '', '', '', 15000, '102', '', 238, 239, 240, 241);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (38, '월곶 1', 4, '', '', '가능', '가능', 10000, '85', '', 242, 243, 244, 245);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (39, '1st room', 2, '', '가능', '가능', '가능', 30000, '103', '', 246, 247, 248, 249);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (40, 'Room', 4, '', '', '가능', '', 0, '104', '', 250, 251, 252, 253);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (41, '선교 복지관', 4, '', '', '', '', 0, '81', '', 259, 260, 261, 262);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (42, '안식관', 4, '', '', '가능', '가능', 0, '73', '', 263, 264, 265, 266);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (43, '선교사쉼터', 4, '', '', '가능', '', 10000, '106', '', 281, 282, 283, 284);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (44, '소망1', 1, '', '', '가능', '가능', 5000, '98', '', 298, 300, 301, 303);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (45, '사랑', 1, '', '', '가능', '가능', 5000, '98', '', 304, 305, 307, 306);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (48, '큰방', 0, '', '', '공동', '공동', 10000, '109', '', 341, 343, 342, 344);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (49, '큰방', 4, '', '가능', '가능', '가능', 15000, '110', '', 475, 346, 358, 476);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (50, '1인침대방1', 1, '', '가능', '가능', '가능', 15000, '110', '', 470, 471, 351, 352);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (51, '1인침대방2', 1, '', '가능', '가능', '가능', 15000, '110', '', 472, 354, 473, 474);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (52, '수양관', 4, '', '', '가능', '가능', 0, '65', '', 374, 375, 376, 377);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (53, '4층 2', 5, '', '가능', '가능', '가능', 30000, '95', '', 394, 395, 396, 397);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (54, '로고스관', 0, '', '', '', '', 0, '111', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (55, '', 0, '', '', '', '', 0, '55', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (57, '벧엘관', 0, '', '', '', '', 13000, '112', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (58, '마므레홀', 0, '', '', '', '', 15000, '113', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (61, '자비(2-4인)', 2, '', '가능', '공동취사', '가능', 5000, '96', '', 403, 404, 405, 406);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (62, '희락(2-4인)', 2, '', '가능', '공동취사', '가능', 5000, '96', '', 399, 400, 401, 402);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (63, '사랑(2-4인)', 2, '', '가능', '공동취사', '가능', 5000, '96', '', 407, 408, 409, 410);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (64, '온유(1-2인)', 4, '', '가능', '공동취사', '가능', 5000, '96', '', 411, 412, 413, 414);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (65, '긍휼(1-2인)', 2, '', '가능', '공동취사', '가능', 5000, '96', '', 415, 416, 417, 418);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (66, '게스트하우스', 0, '', '', '', '', 0, '56', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (68, '선교관1', 2, '', '가능', '가능', '가능', 5000, '117', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (69, '안식관', 5, '', '가능', '가능', '가능', 0, '77', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (70, '2인실,가족실', 2, '', '가능', '가능', '', 10000, '118', '', 421, 422, 424, 425);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (71, '2인실', 2, '', '가능', '가능', '가능', 5000, '53', '', 426, 427, 428, 429);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (72, '원룸', 2, '', '가능', '가능', '가능', 5000, '67', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (73, '수양관', 0, '', '', '', '', 0, '37', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (76, '선릉힐', 2, '', '', '', '', 10000, '59', '', 449, 450, 451, 452);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (77, '2인용', 2, '', '', '', '', 6000, '80', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (78, '방3개', 4, '', '가능', '가능', '가능', 0, '121', '', -1, -1, -1, -1);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (80, '원룸', 4, '', '가능', '가능', '가능', 20000, '123', '', 460, 461, 462, 463);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (81, '사랑방', 4, '', '가능', '가능', '가능', 10000, '124', '', 479, 483, 481, 482);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (82, '원룸', 4, '', '불가', '가능', '가능', 10000, '127', '', 489, 490, 491, 493);

INSERT INTO room
  (roomId, roomName, `limit`, `explain`, network, kitchen, laundary, fee, houseId, document, imageId1, imageId2, imageId3, imageId4)
VALUES
  (83, '쉴터', 2, '', '가능', '가능', '가능', 5000, '130', '', 502, 503, 504, 505);

