INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('adama65', '이봉우', '동일교회', '02-2208-0811', '예장 통합', '02-763-9764', '01228', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :

			', '1.

2.

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('Andrew Lee', '이찬우', '연희교회', '02-333-9942', '한국 인터서브 선교회', '070-7013-0085', '01226', '', '', '', '', '유미희', '010-5339-5862', '@', '간단한 소개 :저는 약사로서 평신도 선교사로 인터서브 선교회 소속으로 1997년에 가족(아내, 세 아이들)들과 함께 파송되어 중앙 아시아 키르기즈스탄에서 사역하고 있습니다. 


사역소개 :지역사회 개발 사역으로 마을에 유치원, 청소년들을 위한 마을 학교에서 러시아어 클럽, 농촌교회 자립을 위한 농업개발 지원, 유치원 교사 양육, 젊은 부부들을 위한 결혼 세미나, 가정 세미나, 부부 세미나 등

			', '1. 예수님을 점점 닮아가는 사역자가 되도록

2. 현지 동역자들을 존중하고 사랑하며 그들과 함께 하는 사역자가 되도록

3. 일하는 마을, 무슬림들이 속히 예수님을 알게 되도록


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('apple802', '', '', '02--', '', '02--', '01999', '', '', '', '', '', '010--', '@', '', '', 0, 0, 114, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('bark2028', '박기철', '금양교회', '055-882-0286', '열방선교회', '053-621-4308', '01999', '833077-52-100488', '농협', '박기철', '', '임선희', '010-7797-8024', 'lim72791@hanmail.net', '간단한 소개 :진주노회 서남시찰 금양교회를 17년10개월 위임목사로 섬기며 하동성시화운동대표본부장, 하동기독교연합회장, 경목, (영호남 4개지역)섬진강변기독교협의회를 만들고 섬기기도하였던 모든 활동을 뒤로하고 오직 땅끝까지 주의 복음전하는 선교사역에 전가족(90세 노모와 세아들 그리고 아내)이 헌신하기로 하여 열방선교회 본부 총무로 먼저 활동하게 되었다.


 사역소개 : 선교사 지원 : 선교사 후생 복지 사역 출국 제반에 관한 업무 지원, 현지 신학교 및 교회 개설 업무, 현지 학교 감사 년 2회,  각종 교안 번역 출판 및 인쇄,  제반사무, 재정 모금 및 후원자 관리, 후원교회를 순회하여 본회 홍보 및 선교 동원, 타 선교단체와 대외 협력 및 사역 공조, 선교에 관한 전략 개발 및 정보보급, 선교대회 유치 등.

			', '1.성령충만

2.열방선교회의 총무사역에 충성하도록, 하나님의 주시는 분별력과 열정이 식지 않도록.

3.필요를 채우시는 하나님의 손길을 늘 누리도록, 가족들이 동일한 은혜를 누릴 수 있도록.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('blackdew', 'ttt', '', '02--', '', '02--', '01101', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :


', '1.

2.

3.

', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('byunggookyoon', '윤병국', '예장총회 세계선교위원회(고신)', '042-622-7061', '예장총회 세계선교위원회(고신)', '042-622-7061', '01216', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :

			', '1.

2.

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('chjphoto', '최한준', '이레교회', '02-992-2274', '한국기아대책기구', '02-2085-8385', '01306', '1103246100063', '신한은행', '최한준', '', '', '010--', '@', '간단한 소개 :평신도선교사로 현재 교회 사역중 , 아내와 아들 2명과 함께현지에 거주, 현재 워싱턴 침신 대학원과정 학업중


사역소개 :파라과이 이따구아에서 교회 사역중, 2년전 3명으로 시작 하여 현재 어른 약 40, 아이들 50명 정도 함게 예배 드림,

			', '1.현재 새 성전 건축을 위해 땅 구입을 준비중(30*40m = 약 20,000불)

2.15년된 중고차를 사용 도로 열악하여 잦은 고장으로 지출과다, 새차 구입이나 3년정도의 중고차를 구입코자 합니다.(약20,000불 이상)

3.자녀들이 현재 현지 대학 재학중 학비를 위해서

4. 가족 건강을 위해서(아내, 류마치스 관절염, 저는 이 치료 임프란크를 해야함)
     또한 치료비를 위해서


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('chjpo7', '최한준', '이레교회', '02-2085-8385', '기아대책기구', '02-2085-8385', '01306', '110324610063', '신한은행', '최한준', '', '', '010--', '@', '간단한 소개 :기아대책기구 소속 평신도 선교사 현재 신대원 재학, 가족4 아들2명 모두 현재 신학대학 재학중, 현지 파라과이에서,, 현재 6년차 


사역소개 :현지 교회 사역중

			', '1.저희 b엘 교회 말씀으로 부흥되는 교회

2.새로운 겅전 건축을 위한 재정을 위해

3.승합차량 필요

4, 가족 건강과 언어 진보를 위해

5, 각자 할겁에 필요한 물질과 지혜와 물질을 위해서


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('cigrace', '박광우', '바울선교회', '053-254-8418', '국제기아대책기구', '02-254-8418', '01101', '076-04-08382-266', '외환은행', '바울선교회', 'www.bauri.org    www.kfhi.or.kr', '최선주', '053-254-8418', 'tpmk86@naver.com', '간단한 소개 :
2000년 파송 이래로 서아프리카 코트디부아르에서 사역중인 선교사입니다. 

사역소개 :
성경사역, 어린이 및 청소년 사역, 기타개발 사역

			', '1.영적,육적으로 건강한 선교사로 늘 사역할 수 있도록

2.돌보는 500여명 아동들과 봉사교사 대학생들, 현지선교사,전도자들에게 영육간에 풍성한 은혜가 넘치도록

3.늘 새로워지는 가운데 주님을 섬기는 선교사가 되도록


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('crystalkim7', '윤장오', '', '02--', '', '02--', '01999', '', '시티은행', '김찬근', '', '', '010--', '@', '간단한 소개 : 윤장오 선교사는 미국 버지니아 리버티 신학교에서 MDiv를 수학하고 동 신학교에서 ThM을 하는 중에 2007년 필리핀에 들어와 현지 필리핀 교회와 협력 사역, 빈민촌 지역의 사역, 교도소 사역을 감당하고 있으며 슬하에 아들 화평(20살) 지금 라살 대학 2학년에 재학 중이고 작은 아이 온유(18살) 지금 라살 대학1학년에 재학 중입니다. 그리고 아내 김수정(45살) 선교사가 함께 사역을 감당하고 있습니다. 

사역소개 :  먼저 저희 가족이 짧은 기간에 여러 사역을 감당할 수 있게 은혜 베풀어 주시는 하나님께 감사를 드립니다. 
먼저 저의 사역을 크게 3부류로 소개하고자 합니다. 
 
첫 번째: 저는 사는 곳에서 2시간 떨어진 라구나 지역 두 곳의 교회와 연결하여 예배 사역을 감당하고 있습니다. John이라는 젊은 목회자와 June이라는 목회자와 함께 그 지역을 복음으로 변화 시키고자 합니다. 말씀 선포를 통한 예배 사역에 목적을 두고 재정 지원 그리고 어려운 아이들에게 장학금 지원을 하며 그리스도의 복음을 전하고 있습니다.       

두 번째: 저희 사는 곳에서 약 30분 떨어진 곳에 코스탈몰이라는 곳의 아주 빈민촌이 있습니다. 그 곳은 전기가 없고 주변에 쓰레기가 많고 냄새가 너무 심해 참으로 마음이 아픈 그러한 곳입니다. 지금 그곳은 물을 공급하고 아이들 학용품과 의료 지원 등을 하며 그 곳 주민들의 마음을 사고 있습니다 이제 저희가 천막이라도 세워 교회를 개척하여 함께 예배를 드리려고 계획 중인데 여러 어려운 상황들이 있어 지연되고 있는 실정입니다. 
그들과 그리스도의 사랑을 함께 나누고자 하는 간절한 마음이 있습니다. 많은 기도가 필요합니다. 

세 번째: 이 땅의 소외되고 연약한 자들을 위한 교도소 선교를 하고 있습니다.  
빠라냐케 교도소와 해마다 Moa 체결을 해서 수감자들과 일부 직원들과 함께 은혜롭게 예배를 드리고 있습니다. 
여기 또한 복음이 절실히 필요한 곳입니다. 예배를 드릴 때마다 저에게는 감동이 있습니다. 처음 그들의 모습은 얼마나 딱딱한지 모릅니다. 그러나 몇 번의 예배를 신령과 진정으로 찬양하고 말씀 전할 때 성령이 충만한 그들의 모습을 발견하게 됩니다. 얼마나 감동의 눈물이 나오는지 모릅니다. 그러나 이 곳에서는 실질 적인 도움을 바라고 있기도 합니다. 
', '1. 필리핀의 한 영혼을 귀하게 생각하는 마음

2. 날마다 성령 충만함으로 하나되는 가족 

3. 필리핀 동역자와의 아름다운 연합


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('dawnwatchmission', '김갑동', '서울효심장로교회', '070-8288-0009', '백석 예수교 장로회 백석총회 평안노회', '070-8288-0009', '01232', '', '', '', '', '조양현', '010-2369-8022', '@', '간단한 소개 :


사역소개 :


', '1.

2.

3.

', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('dosungoo', '도바울', '영광..', '02-2633-5246', 'gcn..', '070-4103-8691', '01223', '168-08-109978', '우리은행', '도성오', '', '김정삼목사', '010-2256-2284', '@', '간단한 소개 :합동측 안주노회 소속이며 2005년에 파송


사역소개 : 어린이 사역

			', '1.문화 사역이 활발하게 이루워 지도록..

2.신변 안전

3 체류비자가 문제 없도록

4. 가족 건강

5. 안정적 후원


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('fimsoo', '김성수', '인천청운교회', '032-544-2341', 'DMS', '070-8235-5167', '01216', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :

			', '1.

2.

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('hossea', '김찬휘', '화성교회(예장 합신)', '02-2606-7701', '알타이선교회', '02-576-8503', '01223', '024-21-0768-365', '국민은행', '김찬휘', 'http://wendeng.church360.net', '유기남', '010-2890-2296', 'altaim@hanmail.net', '간단한 소개 : 저는 예장 합신 서서울노회 소속 목사이고, 알타이선교회 소속으로 중국 산동성 문등시에서 사역하고 있습니다.


사역소개 :
1. ''문등한인교회''를 담임하고 있습니다.
2. 가정교회 지도자들과 가정교회 개척사역을 하고 있습니다.
3. 신학교에서 강의를 하고 있습니다.

			', '1. 문등한인교회가 선교의 거점으로 든든히 설 수 있도록

2. 가정교회 개척과 리더들의 사역을 위해서

3. 두 아들을 위해서
   (큰 아들은 총신대 신학과를 다니다가 2월4일에 입대하였고, 둘째 아들은 금년에 숭실대 기독교학과에 입학하였습니다.)


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('jang', '윤장오', '', '02--', '', '02--', '01232', '', '', '', '', '', '010--', '@', '간단한 소개 : 필리핀의 윤장오 선교사입니다. 저는 1962년생으로 미국 버지니아 리버티 신학교에서 MDiv를 수학하고 동 신학교에서 ThM을 하는 중에 하나님의 인도하심으로 2007년 9월 아내 김수정 그리고 두 자녀와 함께 이곳 필리핀에 오게 되었습니다.

사역소개 : 현지 필리핀 교회와 협력 사역, 빈민촌 사역, 교도소 사역으로 섬기고 있습니다. 저는 예배를 목표로 하고 있으나 구제,의료 그리고 장학 사역등으로 그들을 먼저 돕기를 소망하며 기도하고 있습니다.  

			', '1. 현지 필리핀 사역을 할 때 사람의 생각이 아닌 온전히 하나님의 뜻에 따라 사역을 감당하며 필리핀 사역자와 서로가 영으로 하나가 되어 하나님과 모든 이들이 보기에 아름다운 사역이 될 수 있도록 

2. 교도소의 어려운 환경 속에서 힘들어 하는 주의 백성들을 위로하고 그들에게 주님의 소망을 품게 하므로 출소하여 누구보다도 복음을 담대하게 전할 수 있는 주의 강한 군사로 세워져 가기를 위해 기도 

3. 무엇보다도 가족 모두가 늘 성령 충만하게 하시고 끝까지 주님을 놓지 않고 의지하는 믿음의 가족이 되도록 그리고 모든 영광 오직 하나님께 드리는 겸손한 가족이 되도록 
			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('jhouse1', '선교사', '한국교회와 선교단체', '02--', '교회와 선교단체', '070-7807-6394', '01202', '', '', '', '', '', '010--', '@', '**** 간단한 소개 :

1) 이곳은 추천하실만한 선교사님을 추천하여 후원자를 발굴하고 결연해
 
   드리려고 합니다. 추천된 선교사를 후원하고 싶거나 후원요청이 필요하신 분은

   godlovehouse@nate.com 으로 추천서와 자기소개서를 보내주시면 됩니다. 


2) 사역소개 :
 
  * 여기는 간단한 사역소개를 기재하는 곳입니다. 
			', '1. 좋은 선교사님들과 좋은 후원자님들의 만남이 이곳을 통하여 이루어지면 좋겠습니다.

2. 갓러브하우스를 통하여 좋은 소문이 많이 나면 좋겠습니다.

3. 하나님 감사드립니다. 


			', 0, 1, 494, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('joe71', '정양수', '', '02--', 'wec', '02-529-4552', '01101', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :

			', '1.

2.

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('jw1104', '한종우, 조은경', '', '02--', '중동선교회', '070-8250-3320', '01406', '39908047221', '우리은행', '조은경', '', '', '010--', '@', '간단한 소개 :
요르단에서 6년차 살고 있습니다

사역소개 :
현지교회 사역 외 난민, 현지 센타 방문사역
			', '1. 가족모두가 기쁨과 감사, 기도 가운데 늘 하나님의 뜻을 이뤄가도록

2. 현지 교회가 말씀의 분별력을 가지고 진리 가운데 깨어 일어나고
   예수님의 삶을 실천하며 섬김을 기쁨으로 알도록

3. 자녀들이 현지 학교에서 잘 적응하며 주님의 사랑을 늘 경험하도록


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('kkchina', '김승진', '한빛교회', '02-894-4149', 'GMS', '02-568-9776', '01999', '', '', '', '', '', '010--', '@', '간단한 소개 : 저희 가정은(1남2녀) 2002년 봄에 중국으로 파송되어 9년 반 동안 학교사역과 장족사역을 하다가 재작년 선교지를 변경하게 되어 영국에서 사역하고 있습니다.


사역소개 : 영국 동남부에 위치한 초중고 보딩스쿨인 Felixstowe International College에서 MK, PK 등을 섬기며 학교사역을 하고 있습니다.

			', '1. 저와 저희 가정이 매일 영적으로 살아있게 하여 주옵소서

2. 학교에 더 많은 나라의 준비된 영혼, 준비된 학생들을 보내 주옵소서

3. FIC가 모슬렘권을 향한 전략적인 교육선교의 교두보 역할을 역동적으로 감당하게 하옵소서


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('m10003', '주신실', '월문교회', '02--', 'SOUL 선교회', '02--', '01008', '060-13-28623-8', '외환', '김경숙', '', '박희춘', '011-1701-3589', '@', '간단한 소개 :
I국 선교사. 
미혼이며 오랫동안 방글라데시, 몽골 단기선교와 필리핀 언어연수 및 어린이 사역 등을 준비해왔습니다. 
SOUL 선교회 소속 선교사입니다. 
                  
사역소개 :
I국의 대학교 젊은이들을 대상으로 사역하고 있습니다. 
현지 개종자들과의 기도모임을 통한 연합 활동입니다.
단기팀과의 동원사역
 


', '1.  하루 3시간 이상 기도시간 및 경건시간

2. 학생비자를 장기비자 취득을 위해 기도해 주십시요

3. 현지 믿는자들과 지속적인 전도에 대한 비전제시 및 전도의 문을 열 수 있는 방법제시
', 0, 0, 189, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('m2000210135', '신명철', '신애제일교회', '02-838-3171', 'WEC', '02-529-4552', '01212', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :

			', '1.

2.

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('mission001', '', '', '02--', '', '02--', '01225', '', '', '', '', '', '010--', '@', '', '', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('mission2', '22', '222', '02-222-2222', '222', '02-22-222', '01003', '222', '22', '222', '22', '222', '010-22-222', '22@222', '간단한 소개 :


사역소개 :
222
			', '1.

2.
222
3.


			', 0, 0, 2, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('moonheekz', '이문희', '형제침례교회', '02-233-3960', '침레교해외선교회', '070-8237-5277', '01101', '', '', '', '', '', '010--', '@', '간단한 소개 :인도의 김기태 선교사의 아내 이문희입니다.


사역소개 :카작에서 10년의 사역 후 사역지를 이양하고 인도로 가서 교회를 개척하고 있습니다 

			', '1.새로 시작되는 언어 학교와 개척한 교회가 하나님의 은혜로 열매맺어가도록

2.한국 방문시 병원 진료와 치료가 잘 이루어지도록

3.둘재 아이(김요한) 진로를 하나님이 인도하실때 아들이 기쁘게 따르도록


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('mwkang1024', '', '', '02--', '', '02--', '01102', '', '', '', '', '', '010--', '@', '', '', 0, 0, 235, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('myanmagape', '강대현 전인숙', '김제신안교회', '063-544-5953', '예장(합동) GMS선교회', '02-568-9776', '01008', '010-04-06395-537', '외환', 'GMS (강대현)', '', '김덕실', '010--', 'myanmagape@gmail.com', '* 간단한 소개 :
  미얀마 선교사로 1993년에 총회 파송받음. 2남1녀의 자녀와 함께 미얀마에서 사역하고 있음. 

* 사역소개 :
  초기 교회개척사역 중에 총 9개의 교회를 개척하고 그리고 이제는 교회개척에 필요한 선교원교사를 양육하는 미얀마어린이선교신학교를 운영하고 있음.
  미얀마는 교회개척시 간접적으로 개척해야 되는데. 
전투적인선교원을 통한 교회개척4단계가 중요하게 쓰임받고 있음. 

- 제1단계: 시작의단계로 유아중심의단계,
- 제2단계: 유아의부모중심의단계.
- 제3단계: 유아부모를통한이웃으로확장하는단계.
- 제4단계: 확신의단계(주일학교혹은교회를개척하는 단계)

			', '1. 미얀마 어린이 선교신학교가 잘 운영되게 하시고, 미얀마에 있는 대학이나 그 어느곳에도 유아전담교육기관이 없는 상황에서 우리 어린이 선교 신학교가 어린이 선교와 사회 어린이 교육까지도 리더십을 발휘할 수 있도록 그래서 이 땅의 어린이 교육이 불교식이 아니라 기독교에 입각한 교육을 행할 수 있도독 해 주소서. 

2. 두 자녀가 미국에 있는 대학에 들어갔는데 과도한 교육비가 너무 부담으로 작용하오니 이 문제를 선하게 인도해 주소서.

3. 큰 아들 시온이 신장 속에 있는 이물질 덩어리(약 6센티크기)가 보혈의 능력으로 어루만지시고 성령의 불로 태우소서. 그래서 신장 때문에 피곤해서 감당해야 할 주의 비전을 잃지 않게 하소서.

			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('newacts', '', '', '02--', '', '02--', '01403', '', '', '', '', '', '010--', '@', '', '', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('paul726', '선석완', '이리온누리교회', '063-858-3811', '이리온누리교회', '063-858-3811', '01232', '777-01-0000-417', '국민은행', '선석완', 'www.manilaseoul.or.kr', 'paul sun', '010--', 'paulsun726@gmail.com', '간단한 소개 :필리핀에서 24년 째 사역하고 있습니다


사역소개 :미전도족속 선교

			', '1.선교동역자 보내 주시도록

2.부족신학교가 활성화 되도록

3.아내가 건강하도록


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('powersfn', '윤성복/손여정/경원', '광주포도원교회', '062-675-3004', '', '02--', '01404', '', '', '', 'facebook(에덴의 포도나무)', '', '010--', '@', '간단한 소개 : 안녕하세요? 예루살렘에 살고 있는 윤성복/손여정/경원 선교사입니다. 가정과 교회와 사역과 사업이 늘 평안하시길 기도합니다^^


사역소개 : 이스라엘에서 예배와 기도, 공동체 그리고 기독교 어린이도서관을 운영하고 있습니다.

			', '1. 이스라엘의 회복과 예루살렘의 평화를 위해

2. 진행되는 사역과 섬기는 교회를 위해

3. 가족의 건강과 학업을 위해

4. 재정을 위해
			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('proverbs36', '배석우', '순복음춘천교회', '033-253-2741', '순복음춘천교회', '033-253-2741', '01216', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :

			', '1.

2.

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('rebekahre', '김영인', '빛과소금의 교회', '02-9634-3303', '인터서브', '070-4352-6510', '01223', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :

			', '1.

2.

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('rkatkgody', '신명철/박인숙', '신애제일교회', '02-838-3171', 'WEC', '02-529-4552', '01212', '019-21-1002-031', '국민은행', '신명철', '', '나유진', '010-6314-3813', 'hiworld@hanmail.net', '간단한 소개 :2004년 WEC 호주 MTC 2년을 마치고 2006년 아제르바이잔으로 나갔습니다. 비자의 어려움이 있고 사역적인 부분에서 이슬람국가들이 갖고 있는 난제들이 있지만 기도하며 하나님의 세미한 음성에 귀기울이며 살고 있습니다.


사역소개 :교회 개척사역이 저희 팀의 목표입니다. 

			', '1.비자플랫홈을 위해서 기도해주세요. 지금은 국제NGO 에서 받고 있는데 NGO의 존재여부가 불투명해지고 있어서 하나님의 새로운 인도하심이 필요합니다.

2.박인숙 선교사의 건강을 위해서 기도해주세요. 허리에 척관협착증이 있습니다. 


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('sarangcn', '진훈', '중동교회', '032-322-5599', 'HOPE', '02-533-6057', '01223', '', '', '', '', '', '010--', '@', '간단한 소개 :


사역소개 :

			', '1.

2.

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('sunkyosa', '정형구', '천안중부교회', '041-575-0479', 'GMS', '02-568-9776', '01232', '', '', '', '', '', '010--', '@', '간단한 소개 : 25년째 선교사로 사역하고 있습니다.


사역소개 : 한인교회, 방송선교, 문서선교, 학원선교, 현지인사역등등

			', '1. 가족의 건강을 위해서

2. 사역에 필요한 인력과 장비와 물자를 위해서

3. 부족한 사역비 충당을 위해서


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('timlee', '오충성', '마산재건교회', '055-248-5156', 'WEM', '02-421-0888', '01223', '651-21-0919-921', '국민은행', '이태인', '', '전승훈', '010-3209-2138', '@', '간단한 소개 :
중국선교사(13년째)

사역소개 :
교회개척, 가정교회지도자및 신학생 훈련
			', '1. 한걸음씩 하나님의 인도하심을 잘 받을 수 있도록

2. 숙소가 잘 구해지도록

3.


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('walnut59', '김미미', '삼선교회', '02-742-0475', '삼선교회 협력', '02-742-5174', '01223', '06919432118', '외환은행', '오인열', 'www.samsungchurch.net', '장윤석 목사', '010-9945-0191', '@hanmail.net', '간단한 소개 :1992년 총신대학교 정성구 목사님이 중국으로 파송함.
정목사님 사임후 파송이 끊어짐.
삼선교회는 파송은 아니지만 제 1 선교사임. 
그외 원남교회, 화성 소망교회, 수원 은혜교회등의 협력파송입니다.

사역소개 : 1. 가정교회 개척
               2. 가정교회 사역자 훈련
               3. 도시교회 제자훈련

			', '1. 큰 아들이 사고없이 제대하게 된 것 ₩J사,
    작은 아들이 군대에 가려고 준비중인데 좋은 인도하심 있기를..

2. 한국에 귀국중 3개월정도 거처가 마련되도록

3. 1월에 비자를 갱신해야 하는데 비자가 잘 갱신되도록.




			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('wmpkorea', '김태한', '일산 세광교회', '031-903-3390', '한국 AFC', '02-514-8870', '01999', '820-21-0528839', '국민은행', '김태한', '', '황지현', '02-514-8870', 'afck@afck.or.kr', '간단한 소개 : 2004년 우크라이나에 파송받아 8년째 사역하고 있는 김태한, 윤수정 선교사입니다. 좋은 선교회를 설립하시고 협력하시는 귀한 여러분들의 모습이 아름답습니다. 저도 일원이 되어 함께 선교하고자 합니다. 

사역소개 : 
우크라이나 복음주의 신학교 교수사역
교회 개척 사역 
우크라이나 피스메이커 사역본부 대표
문화원 및 키예프 한글학교 
키예프 크리스천 아카데미 (MK 학교) 이사 	', '1. 성령 충만한 선교사가 되도록

2. 주어진 사역에 최선을 다하는 성실한 선교사가 되도록

3. 현지인을 그리스도의 사람들로 세우는 선교사가 되도록


			', 0, 0, 0, 0);

INSERT INTO missionary
  (userId, missionName, church, churchContact, ngo, ngoContact, nationCode, accountNo, bank, accountName, homepage, manager, managerContact, managerEmail, memo, prayList, familyCount, approval, imageId, flagFamily)
VALUES
  ('yongjunk', '김용준', '한국대학생선교회', '02-397-6200', '한국대학생선교회', '02-397-6200', '01008', '803-01-0144-121', '국민은행', '김용준', 'kccc.org', '정건철', '010-3114-5359', '@', '간단한 소개 : 파송된지 10년이 되었습니다. 아내 두아들이 있습니다


사역소개 :NK쪽 일을 합니다

			', '1. 가족과사역에서 성령충만유지

2. 가족과 팀의 안전유지

3. 후원자들의 지속적인 후원유지


			', 0, 0, 0, 0);

