INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('notice', 'lovehouse', 0, 9, 1, 0, '공지사항');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('free', 'lovehouse', 0, 1, 1, 0, '자유게시판');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('impression', 'lovehouse', 0, 3, 1, 0, '이용후기');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('need', 'lovehouse', 0, 1, 1, 0, '필요게시판');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('share', 'lovehouse', 0, 1, 1, 0, '나눔게시판');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('outgoing', 'lovehouse', 0, 9, 1, 0, '지출게시판');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('column', 'lovehouse', 0, 9, 1, 0, '칼럼');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('event', 'lovehouse', 0, 9, 1, 0, '선교단체행사');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('mission_news', 'lovehouse', 0, 3, 1, 0, '선교지소식');

INSERT INTO boardGroup
  (groupId, managerId, authReadLv, authWriteLv, authCommentLv, countList, name)
VALUES
  ('support_news', 'lovehouse', 0, 9, 1, 0, '후원자소식');

