INSERT INTO account
  (id, number, bank, name, method, nid, userId, sendDate, expectDate, regDate)
VALUES
  (2, '12345784593', '국민', '정진화', '1', '0000000000000', 'lovehouse', 25, 2, UNIX_TIMESTAMP('2009-10-17 00:29:48'));

INSERT INTO account
  (id, number, bank, name, method, nid, userId, sendDate, expectDate, regDate)
VALUES
  (3, '1111111111', '하나은행', '이숙번', '1', '1111111111111', 'blackdew', 25, 1, UNIX_TIMESTAMP('2009-10-22 01:18:32'));

