INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (1, 'UPDATE requestItem SET reqId = ''20'', item = ''자동차구입'', descript = ''자동차구입'', cost = ''8000000'', userId = ''lovehouse'', sendStatus = ''S1002''  WHERE reqItemId = 16', '2010-03-17 18:29:36', '', 0);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (2, 'UPDATE requestItem SET reqId = ''20'', item = ''자동차구입'', descript = ''자동차구입'', cost = ''8000000'', userId = ''lovehouse'', sendStatus = ''S1002''  WHERE reqItemId = 16', '2010-03-17 18:30:40', '', 0);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (3, 'UPDATE requestItem SET reqId = ''20'', item = ''자동차구입'', descript = ''자동차구입'', cost = ''100000'', userId = ''lovehouse'', sendStatus = ''S1002''  WHERE reqItemId = 15', '2010-03-17 18:30:56', '', 0);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (4, 'UPDATE requestItem SET reqId = ''20'', item = ''자동차구입'', descript = ''자동차구입'', cost = ''8000000'', userId = ''lovehouse'', sendStatus = ''S1002''  WHERE reqItemId = 16', '2010-03-17 18:30:56', '', 0);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (9, '', '2010-03-19 10:50:49', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (10, '', '2010-03-19 10:50:56', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (11, '', '2010-03-20 22:06:16', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (12, '', '2010-03-20 22:06:21', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (17, '', '2010-03-20 22:12:08', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (18, '', '2010-03-20 22:12:40', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (19, '', '2010-03-20 22:12:41', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (20, '', '2010-03-20 22:16:54', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (21, '', '2010-03-20 22:16:56', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (22, 'SELECT * from room WHERE roomId = ''27//?menu=http://hbbb.com.au/.../id.jpg?''', '2010-10-27 23:55:47', 'Syntax error converting the varchar value ''27//?menu=http://hbbb.com.au/.../id.jpg?'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (23, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://www.fileden.com/files/2010/11/2/3006906/id.txt??''', '2010-11-14 02:05:23', 'Syntax error converting the varchar value ''27/index.php?menu=http://www.fileden.com/files/2010/11/2/3006906/id.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (24, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://www.fileden.com/files/2010/11/2/3006906/id.txt??''', '2010-11-21 07:13:20', 'Syntax error converting the varchar value ''27/index.php?menu=http://www.fileden.com/files/2010/11/2/3006906/id.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (25, 'SELECT * from room WHERE roomId = ''27/index.php?id_menu=''''''', '2011-01-05 20:15:48', 'Syntax error converting the varchar value ''27/index.php?id_menu='''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (26, 'SELECT * from room WHERE roomId = ''27/index.php?menu=''''''', '2011-01-07 22:31:48', 'Syntax error converting the varchar value ''27/index.php?menu='''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (27, 'SELECT * from room WHERE roomId = ''27/index.php?menu=''''''', '2011-01-07 22:32:07', 'Syntax error converting the varchar value ''27/index.php?menu='''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (28, 'SELECT * from room WHERE roomId = ''27/index.php?menu=test??''', '2011-04-24 17:54:07', 'Syntax error converting the varchar value ''27/index.php?menu=test??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (29, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://sports.singleidea.com/sportsimages/b??''', '2011-04-24 17:54:08', 'Syntax error converting the varchar value ''27/index.php?menu=http://sports.singleidea.com/sportsimages/b??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (30, 'SELECT * from room WHERE roomId = ''27/index.php?menu=test??''', '2011-05-04 19:09:37', 'Syntax error converting the varchar value ''27/index.php?menu=test??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (31, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://mchristensen.com/images/uploads/b??''', '2011-05-04 19:09:39', 'Syntax error converting the varchar value ''27/index.php?menu=http://mchristensen.com/images/uploads/b??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (32, 'SELECT * from room WHERE roomId = ''27/index.php?menu=../../../../../../../../../../../../../../../../proc/self/environ''', '2011-05-06 20:40:09', 'Syntax error converting the varchar value ''27/index.php?menu=../../../../../../../../../../../../../../../../proc/self/environ'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (33, 'SELECT * from room WHERE roomId = ''27//index.php?menu=http://nwmbcms.marketaccess.ca/images/banners/ID-RFI.txt??''', '2011-05-08 23:47:20', 'Syntax error converting the varchar value ''27//index.php?menu=http://nwmbcms.marketaccess.ca/images/banners/ID-RFI.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (34, 'SELECT * from board WHERE id = ''140 and char(124)+user+char(124)=0''', '2011-05-10 04:41:50', 'Syntax error converting the varchar value ''140 and char(124)+user+char(124)=0'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (35, 'SELECT * from board WHERE id = ''140# and char(124)+user+char(124)=0''', '2011-05-10 04:41:50', 'Syntax error converting the varchar value ''140# and char(124)+user+char(124)=0'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (36, 'SELECT * from board WHERE id = ''140 and 1=1''', '2011-05-10 04:41:51', 'Syntax error converting the varchar value ''140 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (37, 'SELECT * from board WHERE id = ''140# and 1=1''', '2011-05-10 04:41:51', 'Syntax error converting the varchar value ''140# and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (38, 'SELECT * from board WHERE id = ''140 and 1=2''', '2011-05-10 04:41:51', 'Syntax error converting the varchar value ''140 and 1=2'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (39, 'SELECT * from board WHERE id = ''140# and 1=2''', '2011-05-10 04:41:51', 'Syntax error converting the varchar value ''140# and 1=2'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (40, 'SELECT * from board WHERE id = ''119 and char(124)+user+char(124)=0''', '2011-05-10 04:41:57', 'Syntax error converting the varchar value ''119 and char(124)+user+char(124)=0'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (41, 'SELECT * from board WHERE id = ''119 and 1=1''', '2011-05-10 04:41:58', 'Syntax error converting the varchar value ''119 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (42, 'SELECT * from board WHERE id = ''119 and 1=2''', '2011-05-10 04:41:58', 'Syntax error converting the varchar value ''119 and 1=2'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (43, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:39:30', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (44, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:39:30', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (45, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:39:30', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (46, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:39:31', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (48, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:42:58', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (49, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:42:58', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (47, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:42:58', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (51, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:47:09', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (55, 'SELECT * from room WHERE roomId = ''27/contact.php''', '2011-07-02 10:39:47', 'Syntax error converting the varchar value ''27/contact.php'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (56, 'SELECT * from room WHERE roomId = ''27/contact.php''', '2011-07-02 10:39:56', 'Syntax error converting the varchar value ''27/contact.php'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (57, 'SELECT * from room WHERE roomId = ''15''''''', '2011-10-06 04:21:37', 'Syntax error converting the varchar value ''15'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (58, 'SELECT * from board WHERE id = ''128 and char(124)+user+char(124)=0''', '2011-12-07 03:00:19', 'Syntax error converting the varchar value ''128 and char(124)+user+char(124)=0'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (59, 'SELECT * from board WHERE id = ''128 and 1=1''', '2011-12-07 03:00:20', 'Syntax error converting the varchar value ''128 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (60, 'SELECT * from board WHERE id = ''128 and 1=2''', '2011-12-07 03:00:20', 'Syntax error converting the varchar value ''128 and 1=2'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (61, 'SELECT * from board WHERE id = ''124 and char(124)+user+char(124)=0''', '2011-12-07 03:00:27', 'Syntax error converting the varchar value ''124 and char(124)+user+char(124)=0'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (62, 'SELECT * from board WHERE id = ''124 and 1=1''', '2011-12-07 03:00:28', 'Syntax error converting the varchar value ''124 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (63, 'SELECT * from board WHERE id = ''124 and 1=2''', '2011-12-07 03:00:28', 'Syntax error converting the varchar value ''124 and 1=2'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (64, 'UPDATE house SET assocName = ''그리심빌리지'', address1 = ''경북 영덕군 남정면 부경리'', address2 = ''10-1'', regionCode = ''02008'', zipcode = ''766843'', explain = ''영적 목마름으로 인하여 영적 충전하고싶은 선교사님!
어디론가 "존 버연" 처럼 길을 나서고 싶은 순례자의 마음은 없습니까?
이곳 영덕 장사의 작은 어촌에 있는 
선교사 게스트 하우스 "그리심 빌리지"로 오세요. 
선교사님의 안식을 도와 드립니다.

1. 예약신청은 반드시 카페 메뉴의 "게스트 하우스 예약하세요!" 란을 참고하셔서 인터넷으로만 예약이 가능합니다. 
2. 신청에 필요한 서류는(신청서,파송증명서.소속증명서) 확인이 필요합니다. 
3. 인터넷 접수만이 가능 합니다. (전화는 잘 받지 않습니다. 외부 활동과 작업에 많은 방해를 받습니다. 그러므로 전화로 접수는 받지 않으며 게스트 하우스에서 남기신 연락처로 연락을 드리도록 하겠습니다.) 

* 더욱 자세한 내용은 홈페이지로 가셔서 공지글과 내용을 자세히 확인하시기 바랍니다.
 
방문하실 때 선교 현지 사역지의 기념될 만한 것 중에 1개품을 헌물해 주시면 선교지와 선교사님을 위해 기도하고 기념으로 "선교사님 방문 기념코너"를 만들어 전시하고자 합니다.자세한 문의는 본 게시판에 남겨 주세요. 
'', userId = ''lovehouse'', manager1 = ''최바울'', contact1 = ''010--'', manager2 = '''', contact2 = ''010--'', price = ''무료'', personLimit = ''4'', roomLimit = ''0'', houseName = ''그리심빌리지'', homepage = ''http://cafe.daum.net/gerizimvillage/78l5/34'', buildingType = ''4'', status = ''S2002'', document = ''test'' documentId = ''-1''  WHERE houseId = 100', '2011-12-27 22:35:31', 'Line 14: Incorrect syntax near ''documentId''.', -2147217900);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (65, 'UPDATE house SET assocName = ''그리심빌리지'', address1 = ''경북 영덕군 남정면 부경리'', address2 = ''10-1'', regionCode = ''02008'', zipcode = ''766843'', explain = ''영적 목마름으로 인하여 영적 충전하고싶은 선교사님!
어디론가 "존 버연" 처럼 길을 나서고 싶은 순례자의 마음은 없습니까?
이곳 영덕 장사의 작은 어촌에 있는 
선교사 게스트 하우스 "그리심 빌리지"로 오세요. 
선교사님의 안식을 도와 드립니다.

1. 예약신청은 반드시 카페 메뉴의 "게스트 하우스 예약하세요!" 란을 참고하셔서 인터넷으로만 예약이 가능합니다. 
2. 신청에 필요한 서류는(신청서,파송증명서.소속증명서) 확인이 필요합니다. 
3. 인터넷 접수만이 가능 합니다. (전화는 잘 받지 않습니다. 외부 활동과 작업에 많은 방해를 받습니다. 그러므로 전화로 접수는 받지 않으며 게스트 하우스에서 남기신 연락처로 연락을 드리도록 하겠습니다.) 

* 더욱 자세한 내용은 홈페이지로 가셔서 공지글과 내용을 자세히 확인하시기 바랍니다.
 
방문하실 때 선교 현지 사역지의 기념될 만한 것 중에 1개품을 헌물해 주시면 선교지와 선교사님을 위해 기도하고 기념으로 "선교사님 방문 기념코너"를 만들어 전시하고자 합니다.자세한 문의는 본 게시판에 남겨 주세요. 
'', userId = ''lovehouse'', manager1 = ''최바울'', contact1 = ''010--'', manager2 = '''', contact2 = ''010--'', price = ''무료'', personLimit = ''4'', roomLimit = ''0'', houseName = ''그리심빌리지'', homepage = ''http://cafe.daum.net/gerizimvillage/78l5/34'', buildingType = ''4'', status = ''S2002'', document = ''test'' documentId = ''-1''  WHERE houseId = 100', '2011-12-27 22:35:45', 'Line 14: Incorrect syntax near ''documentId''.', -2147217900);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (66, 'UPDATE house SET assocName = ''그리심빌리지'', address1 = ''경북 영덕군 남정면 부경리'', address2 = ''10-1'', regionCode = ''02008'', zipcode = ''766843'', explain = ''영적 목마름으로 인하여 영적 충전하고싶은 선교사님!
어디론가 "존 버연" 처럼 길을 나서고 싶은 순례자의 마음은 없습니까?
이곳 영덕 장사의 작은 어촌에 있는 
선교사 게스트 하우스 "그리심 빌리지"로 오세요. 
선교사님의 안식을 도와 드립니다.

1. 예약신청은 반드시 카페 메뉴의 "게스트 하우스 예약하세요!" 란을 참고하셔서 인터넷으로만 예약이 가능합니다. 
2. 신청에 필요한 서류는(신청서,파송증명서.소속증명서) 확인이 필요합니다. 
3. 인터넷 접수만이 가능 합니다. (전화는 잘 받지 않습니다. 외부 활동과 작업에 많은 방해를 받습니다. 그러므로 전화로 접수는 받지 않으며 게스트 하우스에서 남기신 연락처로 연락을 드리도록 하겠습니다.) 

* 더욱 자세한 내용은 홈페이지로 가셔서 공지글과 내용을 자세히 확인하시기 바랍니다.
 
방문하실 때 선교 현지 사역지의 기념될 만한 것 중에 1개품을 헌물해 주시면 선교지와 선교사님을 위해 기도하고 기념으로 "선교사님 방문 기념코너"를 만들어 전시하고자 합니다.자세한 문의는 본 게시판에 남겨 주세요. 
'', userId = ''lovehouse'', manager1 = ''최바울'', contact1 = ''010--'', manager2 = '''', contact2 = ''010--'', price = ''무료'', personLimit = ''4'', roomLimit = ''0'', houseName = ''그리심빌리지'', homepage = ''http://cafe.daum.net/gerizimvillage/78l5/34'', buildingType = ''4'', status = ''S2002'', document = ''test'' documentId = ''-1''  WHERE houseId = 100', '2011-12-27 22:37:05', 'Line 14: Incorrect syntax near ''documentId''.', -2147217900);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (67, 'UPDATE house SET assocName = ''그리심빌리지'', address1 = ''경북 영덕군 남정면 부경리'', address2 = ''10-1'', regionCode = ''02008'', zipcode = ''766843'', explain = ''영적 목마름으로 인하여 영적 충전하고싶은 선교사님!
어디론가 "존 버연" 처럼 길을 나서고 싶은 순례자의 마음은 없습니까?
이곳 영덕 장사의 작은 어촌에 있는 
선교사 게스트 하우스 "그리심 빌리지"로 오세요. 
선교사님의 안식을 도와 드립니다.

1. 예약신청은 반드시 카페 메뉴의 "게스트 하우스 예약하세요!" 란을 참고하셔서 인터넷으로만 예약이 가능합니다. 
2. 신청에 필요한 서류는(신청서,파송증명서.소속증명서) 확인이 필요합니다. 
3. 인터넷 접수만이 가능 합니다. (전화는 잘 받지 않습니다. 외부 활동과 작업에 많은 방해를 받습니다. 그러므로 전화로 접수는 받지 않으며 게스트 하우스에서 남기신 연락처로 연락을 드리도록 하겠습니다.) 

* 더욱 자세한 내용은 홈페이지로 가셔서 공지글과 내용을 자세히 확인하시기 바랍니다.
 
방문하실 때 선교 현지 사역지의 기념될 만한 것 중에 1개품을 헌물해 주시면 선교지와 선교사님을 위해 기도하고 기념으로 "선교사님 방문 기념코너"를 만들어 전시하고자 합니다.자세한 문의는 본 게시판에 남겨 주세요. 
'', userId = ''lovehouse'', manager1 = ''최바울'', contact1 = ''010--'', manager2 = '''', contact2 = ''010--'', price = ''무료'', personLimit = ''4'', roomLimit = ''0'', houseName = ''그리심빌리지'', homepage = ''http://cafe.daum.net/gerizimvillage/78l5/34'', buildingType = ''4'', status = ''S2002'', document = ''test'' documentId = ''-1''  WHERE houseId = 100', '2011-12-27 22:37:16', 'Line 14: Incorrect syntax near ''documentId''.', -2147217900);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (68, 'INSERT INTO hospital (hospitalName, assocName, address1, address2, zipcode, regionCode, explain, userId, manager1, manager2, contact1, contact2, price, personLimit, homepage, documentId, document) VALUES (''삼성병원'',''누구지'',''서울 강남구 일원동 삼성의료원'',''어딘가'',''135710'',''02001'',''삼성의료원 잘하시오'',''누굴까'', ''누구시오'', '''', ''010-111-2111'', ''010-111-111'', '''', ''2'', ''samsunghospital.org'',''-1'', '''')', '2012-02-11 16:05:04', 'Invalid column name ''homepage''.', -2147217900);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (70, 'INSERT INTO hospital (hospitalName, assocName, address1, address2, zipcode, regionCode, explain, userId, manager1, manager2, contact1, contact2, price, personLimit, homepage, documentId, document) VALUES (''삼성병원'',''누구지'',''서울 강남구 일원동 삼성의료원'',''어딘가'',''135710'',''02001'',''삼성의료원 잘하시오'',''누굴까'', ''누구시오'', '''', ''010-111-2111'', ''010-111-111'', '''', ''2'', ''samsunghospital.org'',''-1'', '''')', '2012-02-11 16:06:56', 'Invalid column name ''homepage''.', -2147217900);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (72, 'INSERT INTO hospital (hospitalName, assocName, address1, address2, zipcode, regionCode, explain, userId, manager1, manager2, contact1, contact2, price, personLimit, homepage, documentId, document) VALUES (''삼성병원'',''누구지'',''서울 강남구 일원동 삼성의료원'',''어딘가'',''135710'',''02001'',''삼성의료원 잘하시오'',''누굴까'', ''누구시오'', '''', ''010-111-2111'', ''010-111-111'', '''', ''2'', ''samsunghospital.org'',''-1'', '''')', '2012-02-11 16:08:03', 'Cannot insert the value NULL into column ''hospitalId'', table ''npngjjh.npngjjh.hospital''; column does not allow nulls. INSERT fails.', -2147217873);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (73, 'SELECT * from board WHERE id = ''220#.UAwkeqB15l0.twitter''', '2012-07-23 00:59:34', 'Syntax error converting the varchar value ''220#.UAwkeqB15l0.twitter'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (74, 'SELECT * from board WHERE id = ''220#.UAwkeqB15l0.twitter''', '2012-07-23 01:01:11', 'Syntax error converting the varchar value ''220#.UAwkeqB15l0.twitter'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (75, 'SELECT * from board WHERE id = ''220#.UAwkeqB15l0.twitter''', '2012-07-23 01:01:12', 'Syntax error converting the varchar value ''220#.UAwkeqB15l0.twitter'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (76, 'SELECT * from board WHERE id = ''100 and char(124)+user+char(124)=0''', '2012-09-08 18:33:05', 'Syntax error converting the varchar value ''100 and char(124)+user+char(124)=0'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (77, 'SELECT * from board WHERE id = ''100 and 1=1''', '2012-09-08 18:33:05', 'Syntax error converting the varchar value ''100 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (78, 'SELECT * from board WHERE id = ''100 and 1=2''', '2012-09-08 18:33:06', 'Syntax error converting the varchar value ''100 and 1=2'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (79, 'SELECT * from board WHERE id = ''198''''''', '2012-12-16 19:19:06', 'Syntax error converting the varchar value ''198'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (80, 'SELECT * from board WHERE id = ''198 and 1=1''', '2012-12-16 19:19:16', 'Syntax error converting the varchar value ''198 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (81, 'SELECT * from board WHERE id = ''199-1''', '2012-12-16 19:19:20', 'Syntax error converting the varchar value ''199-1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (82, 'SELECT * from board WHERE id = ''230.com''', '2012-12-16 19:20:52', 'Syntax error converting the varchar value ''230.com'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (84, 'SELECT * from board WHERE id = ''230''''''', '2012-12-16 19:20:59', 'Syntax error converting the varchar value ''230'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (85, 'SELECT * from board WHERE id = ''230/**/and/**/1=1''', '2012-12-16 19:21:17', 'Syntax error converting the varchar value ''230/**/and/**/1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (86, 'SELECT * from board WHERE id = ''-;230''', '2012-12-16 19:21:39', 'Syntax error converting the varchar value ''-;230'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (87, 'SELECT * from board WHERE id = ''226''''''', '2012-12-16 19:22:09', 'Syntax error converting the varchar value ''226'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (103, 'SELECT * from room WHERE roomId = ''-1''''''', '2013-01-31 20:38:59', 'Syntax error converting the varchar value ''-1'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (104, 'SELECT * from board WHERE id = ''-1''''''', '2013-01-31 20:39:09', 'Syntax error converting the varchar value ''-1'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (107, 'SELECT * from board WHERE id = ''235#.USXlAc0MhnE.facebook''', '2013-02-21 18:08:08', 'Syntax error converting the varchar value ''235#.USXlAc0MhnE.facebook'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (108, 'SELECT * from board WHERE id = ''235#.USXlAc0MhnE.facebook''', '2013-02-21 18:15:59', 'Syntax error converting the varchar value ''235#.USXlAc0MhnE.facebook'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (110, 'SELECT * from board WHERE id = ''196 Result:     ;''', '2013-06-08 15:08:15', 'Syntax error converting the varchar value ''196 Result:     ;'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (111, 'SELECT * from board WHERE id = ''247 aNd(6=6)''', '2013-08-05 08:02:01', 'Syntax error converting the varchar value ''247 aNd(6=6)'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (112, 'SELECT * from board WHERE id = ''247 aNd(6=7)''', '2013-08-05 08:02:02', 'Syntax error converting the varchar value ''247 aNd(6=7)'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (113, 'SELECT * from board WHERE id = ''247 aNd(6=6) --''', '2013-08-05 08:02:02', 'Syntax error converting the varchar value ''247 aNd(6=6) --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (114, 'SELECT * from board WHERE id = ''247 aNd(6=7) --''', '2013-08-05 08:02:02', 'Syntax error converting the varchar value ''247 aNd(6=7) --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (115, 'SELECT * from board WHERE id = ''247'''' aNd ''''s'''' lIke ''''s''', '2013-08-05 08:02:02', 'Syntax error converting the varchar value ''247'' aNd ''s'' lIke ''s'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (116, 'SELECT * from board WHERE id = ''247'''' aNd ''''s'''' lIke ''''w''', '2013-08-05 08:02:02', 'Syntax error converting the varchar value ''247'' aNd ''s'' lIke ''w'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (117, 'SELECT * from board WHERE id = ''247''''''', '2013-08-05 08:02:04', 'Syntax error converting the varchar value ''247'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (118, 'SELECT * from board WHERE id = ''247''''''', '2013-08-05 08:02:04', 'Syntax error converting the varchar value ''247'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (119, 'SELECT * from board WHERE id = ''247) and 1 in (1''', '2013-08-05 08:02:04', 'Syntax error converting the varchar value ''247) and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (120, 'SELECT * from board WHERE id = ''247) '''' and 1 in (1''', '2013-08-05 08:02:04', 'Syntax error converting the varchar value ''247) '' and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (121, 'SELECT * from board WHERE id = ''247''''`"(''', '2013-08-05 08:02:04', 'Syntax error converting the varchar value ''247''`"('' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (122, 'SELECT * from board WHERE id = ''247) and len(log10(10))=1 and 1 in (1''', '2013-08-05 08:02:05', 'Syntax error converting the varchar value ''247) and len(log10(10))=1 and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (123, 'SELECT * from board WHERE id = ''247) anD quotename(db_name())>0 and 1 in (1''', '2013-08-05 08:02:05', 'Syntax error converting the varchar value ''247) anD quotename(db_name())>0 and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (124, 'SELECT * from board WHERE id = ''247) oRder bY 1 --''', '2013-08-05 08:02:05', 'Syntax error converting the varchar value ''247) oRder bY 1 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (125, 'SELECT * from board WHERE id = ''247) oRder bY 2 --''', '2013-08-05 08:02:05', 'Syntax error converting the varchar value ''247) oRder bY 2 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (126, 'SELECT * from board WHERE id = ''247) oRder bY 3 --''', '2013-08-05 08:02:05', 'Syntax error converting the varchar value ''247) oRder bY 3 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (127, 'SELECT * from board WHERE id = ''247) oRder bY 4 --''', '2013-08-05 08:02:06', 'Syntax error converting the varchar value ''247) oRder bY 4 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (128, 'SELECT * from board WHERE id = ''247) oRder bY 5 --''', '2013-08-05 08:02:06', 'Syntax error converting the varchar value ''247) oRder bY 5 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (129, 'SELECT * from board WHERE id = ''247) oRder bY 6 --''', '2013-08-05 08:02:06', 'Syntax error converting the varchar value ''247) oRder bY 6 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (130, 'SELECT * from board WHERE id = ''247) oRder bY 7 --''', '2013-08-05 08:02:06', 'Syntax error converting the varchar value ''247) oRder bY 7 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (131, 'SELECT * from board WHERE id = ''247) oRder bY 8 --''', '2013-08-05 08:02:07', 'Syntax error converting the varchar value ''247) oRder bY 8 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (132, 'SELECT * from board WHERE id = ''247) oRder bY 9 --''', '2013-08-05 08:02:07', 'Syntax error converting the varchar value ''247) oRder bY 9 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (133, 'SELECT * from board WHERE id = ''247) oRder bY 10 --''', '2013-08-05 08:02:07', 'Syntax error converting the varchar value ''247) oRder bY 10 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (134, 'SELECT * from board WHERE id = ''247) oRder bY 11 --''', '2013-08-05 08:02:07', 'Syntax error converting the varchar value ''247) oRder bY 11 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (135, 'SELECT * from board WHERE id = ''247) oRder bY 12 --''', '2013-08-05 08:02:08', 'Syntax error converting the varchar value ''247) oRder bY 12 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (136, 'SELECT * from board WHERE id = ''247) oRder bY 13 --''', '2013-08-05 08:02:08', 'Syntax error converting the varchar value ''247) oRder bY 13 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (137, 'SELECT * from board WHERE id = ''247) oRder bY 14 --''', '2013-08-05 08:02:08', 'Syntax error converting the varchar value ''247) oRder bY 14 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (138, 'SELECT * from board WHERE id = ''247) oRder bY 15 --''', '2013-08-05 08:02:08', 'Syntax error converting the varchar value ''247) oRder bY 15 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (139, 'SELECT * from board WHERE id = ''247) oRder bY 16 --''', '2013-08-05 08:02:08', 'Syntax error converting the varchar value ''247) oRder bY 16 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (140, 'SELECT * from board WHERE id = ''247) oRder bY 17 --''', '2013-08-05 08:02:09', 'Syntax error converting the varchar value ''247) oRder bY 17 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (141, 'SELECT * from board WHERE id = ''247) oRder bY 18 --''', '2013-08-05 08:02:09', 'Syntax error converting the varchar value ''247) oRder bY 18 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (142, 'SELECT * from board WHERE id = ''247) oRder bY 19 --''', '2013-08-05 08:02:09', 'Syntax error converting the varchar value ''247) oRder bY 19 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (143, 'SELECT * from board WHERE id = ''247) oRder bY 20 --''', '2013-08-05 08:02:09', 'Syntax error converting the varchar value ''247) oRder bY 20 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (144, 'SELECT * from board WHERE id = ''247) oRder bY 21 --''', '2013-08-05 08:02:09', 'Syntax error converting the varchar value ''247) oRder bY 21 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (145, 'SELECT * from board WHERE id = ''247) oRder bY 22 --''', '2013-08-05 08:02:10', 'Syntax error converting the varchar value ''247) oRder bY 22 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (146, 'SELECT * from board WHERE id = ''247) oRder bY 23 --''', '2013-08-05 08:02:10', 'Syntax error converting the varchar value ''247) oRder bY 23 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (147, 'SELECT * from board WHERE id = ''247) oRder bY 24 --''', '2013-08-05 08:02:10', 'Syntax error converting the varchar value ''247) oRder bY 24 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (148, 'SELECT * from board WHERE id = ''247) oRder bY 25 --''', '2013-08-05 08:02:10', 'Syntax error converting the varchar value ''247) oRder bY 25 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (149, 'SELECT * from board WHERE id = ''247) oRder bY 26 --''', '2013-08-05 08:02:10', 'Syntax error converting the varchar value ''247) oRder bY 26 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (150, 'SELECT * from board WHERE id = ''247) oRder bY 27 --''', '2013-08-05 08:02:11', 'Syntax error converting the varchar value ''247) oRder bY 27 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (151, 'SELECT * from board WHERE id = ''247) oRder bY 28 --''', '2013-08-05 08:02:11', 'Syntax error converting the varchar value ''247) oRder bY 28 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (152, 'SELECT * from board WHERE id = ''247) oRder bY 29 --''', '2013-08-05 08:02:11', 'Syntax error converting the varchar value ''247) oRder bY 29 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (153, 'SELECT * from board WHERE id = ''247) oRder bY 30 --''', '2013-08-05 08:02:11', 'Syntax error converting the varchar value ''247) oRder bY 30 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (154, 'SELECT * from board WHERE id = ''247) oRder bY 31 --''', '2013-08-05 08:02:11', 'Syntax error converting the varchar value ''247) oRder bY 31 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (155, 'SELECT * from board WHERE id = ''247) oRder bY 32 --''', '2013-08-05 08:02:12', 'Syntax error converting the varchar value ''247) oRder bY 32 --'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (156, 'SELECT * from board WHERE id = ''247) and (select len(db_name())) between 0 and 30 and 1 in (1''', '2013-08-05 08:02:12', 'Syntax error converting the varchar value ''247) and (select len(db_name())) between 0 and 30 and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (157, 'SELECT * from board WHERE id = ''247) and (select len(db_name())) between 0 and 15 and 1 in (1''', '2013-08-05 08:02:12', 'Syntax error converting the varchar value ''247) and (select len(db_name())) between 0 and 15 and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (5, 'UPDATE requestItem SET reqId = ''20'', item = ''자동차구입'', descript = ''자동차구입'', cost = ''100000'', userId = '''', sendStatus = ''S1001''  WHERE reqItemId = 15', '2010-03-17 18:31:10', '', 0);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (6, 'UPDATE requestItem SET reqId = ''20'', item = ''자동차구입'', descript = ''자동차구입'', cost = ''8000000'', userId = ''lovehouse'', sendStatus = ''S1002''  WHERE reqItemId = 16', '2010-03-17 18:31:10', '', 0);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (7, 'UPDATE requestItem SET reqId = ''57'', item = ''기타물품#1'', descript = ''그외 기타물품구입비'', cost = ''20000'', userId = ''lovehouse'', sendStatus = ''S1002''  WHERE reqItemId = 29', '2010-03-17 18:31:22', '', 0);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (8, 'UPDATE requestItem SET reqId = ''57'', item = ''기타물품#2'', descript = ''그외 기타물품구입비'', cost = ''30000'', userId = ''lovehouse'', sendStatus = ''S1002''  WHERE reqItemId = 30', '2010-03-17 18:31:22', '', 0);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (83, 'SELECT * from board WHERE id = ''230.com''', '2012-12-16 19:20:55', 'Syntax error converting the varchar value ''230.com'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (105, 'SELECT * from board WHERE id = ''-1''''''', '2013-01-31 20:40:15', 'Syntax error converting the varchar value ''-1'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (158, 'SELECT * from board WHERE id = ''247) and (select len(db_name())) between 0 and 7 and 1 in (1''', '2013-08-05 08:02:12', 'Syntax error converting the varchar value ''247) and (select len(db_name())) between 0 and 7 and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (159, 'SELECT * from board WHERE id = ''247) and (select len(db_name())) between 0 and 3 and 1 in (1''', '2013-08-05 08:02:12', 'Syntax error converting the varchar value ''247) and (select len(db_name())) between 0 and 3 and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (160, 'SELECT * from board WHERE id = ''247) and (select len(db_name())) between 0 and 1 and 1 in (1''', '2013-08-05 08:02:13', 'Syntax error converting the varchar value ''247) and (select len(db_name())) between 0 and 1 and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (161, 'SELECT * from board WHERE id = ''247) and (select len(db_name())) between 0 and 0 and 1 in (1''', '2013-08-05 08:02:13', 'Syntax error converting the varchar value ''247) and (select len(db_name())) between 0 and 0 and 1 in (1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (162, 'SELECT * from board WHERE id = ''247 and user=0 and 1=1''', '2013-08-05 08:02:16', 'Syntax error converting the varchar value ''247 and user=0 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (163, 'SELECT * from board WHERE id = ''247 and user=0 and 1=1''', '2013-08-05 08:02:17', 'Syntax error converting the varchar value ''247 and user=0 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (164, 'SELECT * from board WHERE id = ''247 and user=0--''', '2013-08-05 08:02:17', 'Syntax error converting the varchar value ''247 and user=0--'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (165, 'SELECT * from board WHERE id = ''247 and user=0--''', '2013-08-05 08:02:17', 'Syntax error converting the varchar value ''247 and user=0--'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (166, 'SELECT * from board WHERE id = ''247'''' and user=0 and ''''1''''=''''1''', '2013-08-05 08:02:18', 'Syntax error converting the varchar value ''247'' and user=0 and ''1''=''1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (167, 'SELECT * from board WHERE id = ''247'''' and user=0 and ''''1''''=''''1''', '2013-08-05 08:02:19', 'Syntax error converting the varchar value ''247'' and user=0 and ''1''=''1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (168, 'SELECT * from board WHERE id = ''247 and 3=3''', '2013-08-05 08:02:19', 'Syntax error converting the varchar value ''247 and 3=3'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (169, 'SELECT * from board WHERE id = ''247'''' and ''''a''''=''''a''', '2013-08-05 08:02:19', 'Syntax error converting the varchar value ''247'' and ''a''=''a'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (170, 'SELECT * from board WHERE id = ''247''''''', '2013-08-05 08:02:21', 'Syntax error converting the varchar value ''247'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (171, 'SELECT * from board WHERE id = ''247 and user=0 and 1=1''', '2013-08-05 08:02:22', 'Syntax error converting the varchar value ''247 and user=0 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (172, 'SELECT * from board WHERE id = ''247 and user=0 and 1=1''', '2013-08-05 08:02:22', 'Syntax error converting the varchar value ''247 and user=0 and 1=1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (173, 'SELECT * from board WHERE id = ''247 and user=0--''', '2013-08-05 08:02:23', 'Syntax error converting the varchar value ''247 and user=0--'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (174, 'SELECT * from board WHERE id = ''247 and user=0--''', '2013-08-05 08:02:23', 'Syntax error converting the varchar value ''247 and user=0--'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (175, 'SELECT * from board WHERE id = ''247'''' and user=0 and ''''1''''=''''1''', '2013-08-05 08:02:24', 'Syntax error converting the varchar value ''247'' and user=0 and ''1''=''1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (176, 'SELECT * from board WHERE id = ''247'''' and user=0 and ''''1''''=''''1''', '2013-08-05 08:02:24', 'Syntax error converting the varchar value ''247'' and user=0 and ''1''=''1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (177, 'SELECT * from board WHERE id = ''247 and 3=3''', '2013-08-05 08:02:25', 'Syntax error converting the varchar value ''247 and 3=3'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (178, 'SELECT * from board WHERE id = ''247'''' and ''''a''''=''''a''', '2013-08-05 08:02:25', 'Syntax error converting the varchar value ''247'' and ''a''=''a'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (13, '', '2010-03-20 22:06:22', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (14, '', '2010-03-20 22:06:36', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (15, '', '2010-03-20 22:10:17', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (16, '', '2010-03-20 22:10:19', 'Command text was not set for the command object.', -2147217908);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (109, 'SELECT * from board WHERE id = ''235#.USXlAc0MhnE.facebook''', '2013-02-23 15:25:07', 'Syntax error converting the varchar value ''235#.USXlAc0MhnE.facebook'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (50, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:42:58', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (53, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:59:15', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (54, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:59:30', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (106, 'SELECT * from board WHERE id = ''-1''''''', '2013-01-31 20:40:22', 'Syntax error converting the varchar value ''-1'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (52, 'SELECT * from room WHERE roomId = ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??''', '2011-06-04 01:47:09', 'Syntax error converting the varchar value ''27/index.php?menu=http://tal.ohhappy.net/counter/documents/logon.txt??'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (69, 'INSERT INTO hospital (hospitalName, assocName, address1, address2, zipcode, regionCode, explain, userId, manager1, manager2, contact1, contact2, price, personLimit, homepage, documentId, document) VALUES (''삼성병원'',''누구지'',''서울 강남구 일원동 삼성의료원'',''어딘가'',''135710'',''02001'',''삼성의료원 잘하시오'',''누굴까'', ''누구시오'', '''', ''010-111-2111'', ''010-111-111'', '''', ''2'', ''samsunghospital.org'',''-1'', '''')', '2012-02-11 16:06:20', 'Invalid column name ''homepage''.', -2147217900);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (71, 'INSERT INTO hospital (hospitalName, assocName, address1, address2, zipcode, regionCode, explain, userId, manager1, manager2, contact1, contact2, price, personLimit, homepage, documentId, document) VALUES (''삼성병원'',''누구지'',''서울 강남구 일원동 삼성의료원'',''어딘가'',''135710'',''02001'',''삼성의료원 잘하시오'',''누굴까'', ''누구시오'', '''', ''010-111-2111'', ''010-111-111'', '''', ''2'', ''samsunghospital.org'',''-1'', '''')', '2012-02-11 16:07:57', 'Cannot insert the value NULL into column ''hospitalId'', table ''npngjjh.npngjjh.hospital''; column does not allow nulls. INSERT fails.', -2147217873);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (88, 'SELECT * from board WHERE id = ''225 and user=0--''', '2012-12-16 19:41:51', 'Syntax error converting the varchar value ''225 and user=0--'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (89, 'SELECT * from board WHERE id = ''225 and user=0--''', '2012-12-16 19:41:52', 'Syntax error converting the varchar value ''225 and user=0--'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (90, 'SELECT * from board WHERE id = ''225'''' and user=0 and ''''1''''=''''1''', '2012-12-16 19:41:53', 'Syntax error converting the varchar value ''225'' and user=0 and ''1''=''1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (91, 'SELECT * from board WHERE id = ''225'''' and user=0 and ''''1''''=''''1''', '2012-12-16 19:41:53', 'Syntax error converting the varchar value ''225'' and user=0 and ''1''=''1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (92, 'SELECT * from board WHERE id = ''225 and 3=3''', '2012-12-16 19:41:54', 'Syntax error converting the varchar value ''225 and 3=3'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (93, 'SELECT * from board WHERE id = ''225'''' and ''''a''''=''''a''', '2012-12-16 19:41:54', 'Syntax error converting the varchar value ''225'' and ''a''=''a'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (94, 'SELECT * from board WHERE id = ''225''''''', '2012-12-16 19:41:56', 'Syntax error converting the varchar value ''225'''' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (95, 'SELECT * from board WHERE id = ''225 and user=0''', '2012-12-16 19:41:57', 'Syntax error converting the varchar value ''225 and user=0'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (96, 'SELECT * from board WHERE id = ''225 and user=0''', '2012-12-16 19:41:58', 'Syntax error converting the varchar value ''225 and user=0'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (97, 'SELECT * from board WHERE id = ''225 and user=0--''', '2012-12-16 19:41:58', 'Syntax error converting the varchar value ''225 and user=0--'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (98, 'SELECT * from board WHERE id = ''225 and user=0--''', '2012-12-16 19:41:58', 'Syntax error converting the varchar value ''225 and user=0--'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (99, 'SELECT * from board WHERE id = ''225'''' and user=0 and ''''1''''=''''1''', '2012-12-16 19:42:00', 'Syntax error converting the varchar value ''225'' and user=0 and ''1''=''1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (100, 'SELECT * from board WHERE id = ''225'''' and user=0 and ''''1''''=''''1''', '2012-12-16 19:42:00', 'Syntax error converting the varchar value ''225'' and user=0 and ''1''=''1'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (101, 'SELECT * from board WHERE id = ''225 and 3=3''', '2012-12-16 19:42:00', 'Syntax error converting the varchar value ''225 and 3=3'' to a column of data type int.', -2147217913);

INSERT INTO debug_query_list
  (id, query, regDate, errMessage, errNumber)
VALUES
  (102, 'SELECT * from board WHERE id = ''225'''' and ''''a''''=''''a''', '2012-12-16 19:42:01', 'Syntax error converting the varchar value ''225'' and ''a''=''a'' to a column of data type int.', -2147217913);

