INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (6, 4, 1, 50000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (7, 4, 2, 10000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (15, 6, 57, 150000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (27, 6, 20, 200000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (28, 8, 57, 230000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (38, 8, 20, 8000000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (40, 10, 3, 0);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (41, 9, 4, 0);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (42, 11, 66, 0);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (49, 12, 7, 0);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (50, 3, 1, 50000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (51, 3, 12, 50000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (52, 3, 60, 50000);

INSERT INTO supportItem
  (supItemId, supId, reqId, cost)
VALUES
  (53, 5, 3, 0);

