INSERT INTO test
  (id, `name`)
VALUES
  (1, '%');

INSERT INTO test
  (id, `name`)
VALUES
  (2, ''']');

INSERT INTO test
  (id, `name`)
VALUES
  (3, 'asdfl%;''dfd');

INSERT INTO test
  (id, `name`)
VALUES
  (4, '\');

INSERT INTO test
  (id, `name`)
VALUES
  (5, '_');

INSERT INTO test
  (id, `name`)
VALUES
  (6, '[]');

INSERT INTO test
  (id, `name`)
VALUES
  (7, '[test]');

INSERT INTO test
  (id, `name`)
VALUES
  (8, '[test]');

